### ISSUE TITLE
Not possible to format NumericUpDown value as hexidecimal

### ISSUE THREAD

**Issue by AmyAmy** [MahApps/MahApps.Metro#1375]
I think this has to do with the fact that a double is used as storage, which doesn't accept "X" or related formats.

Is there a known workaround for this?

**Comment by punker76** [comment]
@xxMUROxx maybe another issue for you ;-) thx

**Comment by xxMUROxx** [comment]
@punker76 yes

**Comment by thoemmi** [comment]
Don't say I didn't warn you in [#2059](https://github.com/MahApps/MahApps.Metro/issues/2059#issuecomment-126588019) :wink:

**Comment by xxMUROxx** [comment]
#2059 was about adding a new property, this issue is about StringFormat.

Furthermore I dont’t know why #2065 was actually merged, because the discussion was in my opinion clear not to.





From: Thomas Freudenberg
Sent: ‎Monday‎, ‎November‎ ‎9‎, ‎2015 ‎8‎:‎44‎ ‎PM
To: MahApps/MahApps.Metro
Cc: michael.mairegger@yahoo.de





Don't say I didn't warn you in #2059  :wink:
