### ISSUE TITLE
Can we expect a 'Metro' style for the 'Frame' navigation control ?

### ISSUE THREAD

**Issue by aybe** [MahApps/MahApps.Metro#1599]
Hello,

A picture is worth a thousand words, so here is one:

![snap0576](https://cloud.githubusercontent.com/assets/1537591/4738142/e9f64d7e-59fa-11e4-9997-b98e8e4eacb9.png)

Do you have any plans to 'Metro-ize' the `Frame` control navigation UI in a future release ?

Thank you.

**Comment by predlona** [comment]
how can we add a homepage button if possible ? btw sorry for dump.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
