### ISSUE TITLE
MahApps.Metro broken after NuGet update

### ISSUE THREAD

**Issue by cbates-** [MahApps/MahApps.Metro#1806]
Had 0.13.x, installed 1.0 via NuGet.  
Whole raft of strange errors, such as:   
App.xaml:    
<controls:MetroWindow.WindowCommands> -->  Error	13	The member "WindowCommands" is not recognized or is not accessible.	  
  
MainView.xaml:    
vm:ViewModelLocator x:Key="Locator" d:IsDataSource="True"   --> Error	2	The name "ViewModelLocator" does not exist in the namespace "clr-namespace:ProdoMetro.ViewModel".	  
  
What is going on, and how do I fix it?  
  
Thanks --

**Comment by punker76** [comment]
@cbates- there are some changes happend since 0.13

-> https://github.com/MahApps/MahApps.Metro/blob/master/docs/release-notes/0.14.0.md
-> https://github.com/MahApps/MahApps.Metro/blob/master/docs/release-notes/1.0.0.md
-> https://github.com/MahApps/MahApps.Metro/blob/master/docs/v1.0-Migration-Guide.md
-> http://mahapps.com/guides/quick-start.html#customization

**Comment by cbates-** [comment]
Thanks for the quick reply!  I updated via cmd line to v0.14, then to v1.0.  My app builds and appears to run as expected.
