### ISSUE TITLE
Corner resize doesn't work with glow border or drop shadow

### ISSUE THREAD

**Issue by mikecousins** [MahApps/MahApps.Metro#1832]
If you turn either glow border or drop shadow on you can no longer resize from the corner. It will only resize horizontally or vertically, not both.

MahApps Version: 1.1.2.0
OS: Windows 8.1 Pro x64

**Comment by punker76** [comment]
@mikecousins please test the latest alpha, the issue should be fixed there

**Comment by seldgit** [comment]
Hello,

# Confirming that...
* Bug is present in version 1.1.2.0 and behaviour is *somewhat* better, if in MetroWindow you set ResizeMode="CanResizeWithGrip"
* Bug is **fixed in version 1.1.3-ALPHA021 (Prerelease)**, installed from NuGet

# Possible bug with CanResizeWithGrip

In version 1.1.3-ALPHA021, if you set ResizeMode="CanResizeWithGrip", there grip appears in the corner of the screen, but you cannot resize the window by dragging the grip. 

I checked behavior of Visual Studio 2012 and I see that you can actually resize the window by dragging the grip and mouse cursor changes accordingly when you hover over the grip.

Seems like a bug, should I open a "New issue" for it?
