### ISSUE TITLE
External waitable message box like external dialog

### ISSUE THREAD

**Issue by Dimigergo** [MahApps/MahApps.Metro#1846]
I need an external messagebox which has buttons, and I need to wait the user interaction. The awaitable ShowMessageAsync is perfect for me, but it has no externally shown version like ShowDialogExternally function.

Is there any trick to make the external dialog waitable?

Thank you in advance.

**Comment by Amrykid** [comment]
That is something I didn't really take into account when creating the dialogs system. External dialogs are synchronous because they run on their own message loop provided by the invisible window they run in.

If you want to be able to await an external dialog, you need to show it and then hook into it's closing event with a TaskCompletionSource<object> object.

Await on the TaskCompletionSource's Task object.

**Comment by punker76** [comment]
@Dimigergo you can also use a custom dialog and style it like the internal message. hope that helps you.
