### ISSUE TITLE
Me.ShowMessageAsync and MultiThreading

### ISSUE THREAD

**Issue by furiousbuilder** [MahApps/MahApps.Metro#1905]
Hi, 

I'm actually trying in VB.Net to start another thread but it seems impossible if I show a MahApps message box inside like this : 

Private Sub MySub
(MyCode...)
Try
(...)
Me.ShowMessageAsync("Title","text")
Catch Ex As Exception
Me.ShowMessageAsync("Title","text")
End Try
End Sub

![capture d ecran 3](https://cloud.githubusercontent.com/assets/10899984/7375867/b4c558be-eddb-11e4-946f-7028ff8f0c3d.png)

**Comment by Dotnetifier** [comment]
That is how multi-threading works in the .NET Framework.

You have the UI thread, on which your window and all the elements inside are running. There is also your own thread where you are probably doing some CPU-intensive work. This second thread cannot access the UI thread because the UI thread owns that window and accessing it might cause other exceptions.

See [StackOverflow](http://stackoverflow.com/questions/9732709/the-calling-thread-cannot-access-this-object-because-a-different-thread-owns-it) for further details. The accepted answer would in VB.NET be
```
Me.Dispatcher.BeginInvoke(Sub()
                              Me.ShowMessageAsync("Title", "Text")
                          End Sub)
```

**Comment by furiousbuilder** [comment]
Thank you so much ! :D
