### ISSUE TITLE
Flyout title appears under the content

### ISSUE THREAD

**Issue by MedoElkamaly** [MahApps/MahApps.Metro#1973]
when i use the top flyout the title is placed under the content like below 
![flyout](https://cloud.githubusercontent.com/assets/5602736/8120587/8220c6e6-10a9-11e5-9cde-7191cebd961c.PNG)

how to resolve it and make title above the content

**Comment by Dotnetifier** [comment]
This is a Flyout with its Position property set to top, therefore the Header and the close button are centered vertically. You may want to set the `CloseButtonVisibility` property to `Collapsed` and set the Header property to an empty string, and build your own close button and header in a Grid so that they are positioned above the tiles.

**Comment by punker76** [comment]
@MedoElkamaly do you mean the vertical alignment of the flyout button and title 'Options'?
