### ISSUE TITLE
ShowMessageAsync above modal window

### ISSUE THREAD

**Issue by Dimigergo** [MahApps/MahApps.Metro#1974]
Hello,

I would like to use the ShowMessageAsync method to show a message when a modal dialog window is opened.
My possibilities:
1. Message window parent is the modal window. In this case the message is shown only in the smaller dialog window. Only the modal window goes darker.
2. Message window parent is the main application window. It is ok, the message is shown (going dark) all the full screen, but the dialog window is still white, and top, and hide the message window.
3. Use External dialog window -  Everything is ok, but in this case every message window is styled from external dialog window, but the "YesNo" message dialogs has another style (going darker).

I would like to use the same style for my application, so my best choice would be the 2. possibility, but the modal dialog hides my message. :(

Thanks in advance!

**Comment by IsNull** [comment]
I face the same issue. Displaying a MessageBox ontop of a modal dialog or the progress dialog does not work.

Maybe it is not to hard to enhance the integrated modal dialgo system so that it supports stacking multiple dialogs. This would then allow to open any number of modal dialogs / message boxes and they would just be displayed on top of each other.

**Comment by thoemmi** [comment]
I encountered the same issue. At least #1998 improves the overlay handling.

However, the current implementation is not suited to have multiple dialogs (and message boyes) open, e.g. all dialogs but the topmost should be covered by the overlay.

**Comment by IsNull** [comment]
I just digged a bit into the dialog code. The DialogManager Util does not much more than adding the dialog visual to the `internal Grid metroDialogContainer` Grid. I think that just adding more dialog views there should pretty much have the desired effect since they would just overlap.

Wont be perfect but still better than just consuming the whole dialog / message box. I will try to patch this and allow simple stacking of the dialogs.

**Comment by thoemmi** [comment]
You'll need another grid behind the overlay control. `metroDialogContainer` must contain the topmost dialog only, all other dialogs must be put into a "`metroInactiveDialogContainer`".
