### ISSUE TITLE
Progress ring not activating before function call

### ISSUE THREAD

**Issue by crclayton** [MahApps/MahApps.Metro#2000]
I have this progress ring

            <controls:ProgressRing Name="Wait"
                                   Panel.ZIndex="1000"
                                   IsActive="False" />

And this function

        private void DoSomething_Click(object sender, RoutedEventArgs e)
        {
            Wait.IsActive = true;
            doSomething();
            Wait.IsActive = false;
        }

However, the progress ring is never shown while the function is running.

If I comment out the last line, then I'll only see the progress ring after the function is finished running.

I also tried

            <controls:ProgressRing Name="Wait"
                                   Panel.ZIndex="1000"
                                   IsActive="True"
                                   Visibility="Hidden" />

With

            Wait.Visibility = Visibility.Visible;
            doSomething();
            Wait.Visibility = Visibility.Hidden;

With the same effect. It only becomes visible after the function is complete. What am I missing?

Thanks in advance.

**Comment by thoemmi** [comment]
Your code is running in the GUI thread. The control can't react to `Wait.Visibility` because the UI is blocked by `doSomething()`. Try ro rewite your code asynchronously.

**Comment by crclayton** [comment]
Thanks for the response. I don't understand though, why wouldn't the `Wait.IsActive = true;` line complete before `doSomething();` starts?

**Comment by thoemmi** [comment]
Because the storyboard for the animation is blocked.

1. Changing `Visibility` [changes](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/ProgressRing.cs#L33-L48) `IsActive`
2. Setting `IsActive` [changes the visual state](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/ProgressRing.cs#L159-L182)
3. The change of the visual state [starts the storyboard](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/ProgressRing.xaml#L61-L62).

**Comment by deepak-rathi** [comment]
@crclayton  You can do something like this:

private void DoSomething_Click(object sender, RoutedEventArgs e)
    {
      //Make Progress Ring Visible/active
      Wait.IsActive = true;

      BackgroundWorker worker = new BackgroundWorker();
      worker.DoWork += worker_DoWork;
      worker.RunWorkerCompleted += new         RunWorkerCompletedEventHandler(worker_RunWorkerCompleted);
      worker.RunWorkerAsync();
}

 void worker_DoWork(object sender, DoWorkEventArgs e)
 {
     doSomething();
 }

 protected void worker_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
 {
      //Make Progress Ring inActive/hidden
      Wait.IsActive = false;
 }

Close the issue if this helps you :)

**Comment by crclayton** [comment]
Thanks @deepak-rathi , you nailed it. Works perfectly.

**Comment by akshithrajesh290** [comment]
Hi I followed the same process ! 
I got  1 Issue Stating that "the-calling-thread-cannot-access-this-object-because-a-different-thread-owns-it"

So I placed the Below Code

this.Dispatcher.Invoke((Action)(() =>
    {
        ...// your code here.
    }));
I set the Property of the Progress ring to visibility to Visibility.True

It was not showing the Progress Ring (It was not Activating ). 

Again By default  I set the property of  Progress Ring  to Visibility.True on Page Load itself

This Time doWorkerAsync() Method closes the Progress Ring
