### ISSUE TITLE
Databound TreeviewItem does not respond to changes when inside Mahapps window. (Sample Project attached)

### ISSUE THREAD

**Issue by pothmann** [MahApps/MahApps.Metro#2038]
Hello,

i have a TreeView control which has TreeviewItems bound to a viewmodel. In a standard Window the tree reflects changes to IsVisible, IsExpanded and IsSelected properties. But this does not work as soon as tree is in a mahapps window.

![sample](https://cloud.githubusercontent.com/assets/1508765/8744343/c8ac863e-2c76-11e5-977c-175154ff3215.PNG)

I created a solution that directly shows the problem, so that you can quickly see what this issue is about.

http://portalvhdstlvf6zph5075c.blob.core.windows.net/exchange/TreeViewWpfApplication.7z

**Comment by punker76** [comment]
@pothmann there are 2 points in this issue:
1. MahApps should not set the `MetroTreeViewItem` style as the `ItemContainerStyle`, this is fixed with 6cc298ba49d3b39a95769d6ca3b9d5ba3c4386ec
2. you should inherit the `TreeViewItem` style

```xaml
        <Style TargetType="{x:Type TreeViewItem}" BasedOn="{StaticResource {x:Type TreeViewItem}}">
            <Setter Property="Visibility"
                    Value="{Binding IsVisible, Converter={StaticResource BooleanToVisibilityConverter}}" />
            <Setter Property="IsExpanded"
                    Value="{Binding IsExpanded}" />
            <Setter Property="IsSelected"
                    Value="{Binding IsSelected}" />

        </Style>
```

![image](https://cloud.githubusercontent.com/assets/658431/8761719/494dd9c0-2d60-11e5-8ce6-c0d92fd988d0.png)

![image](https://cloud.githubusercontent.com/assets/658431/8761720/4cb2346c-2d60-11e5-81bf-0d7b5ca05eb1.png)
