### ISSUE TITLE
Fill DropDownButton items without Binding

### ISSUE THREAD

**Issue by Iworb** [MahApps/MahApps.Metro#2078]
Is there a way to create DropDownButton without Binding? I've trired to add Buttons into "Items" property or create ContextMenu, but all the same - DropDown part always empty, instead of Binding way.
I just wanna create some DropDownButton menu with hierarchy like that:
    Add:
    - To 1st list
    - To 2nd list

**Comment by QuantumDeveloper** [comment]
Yeah, this is my fault. This control was designed only for MVVM, but I think I could modify it to use items without binding

**Comment by Iworb** [comment]
It should be great if this control can hold Buttons like DropDownButtons in other packs, because I have no idea how this one could be used, because he has no SelectedItem property... Looks like Button with tooltip of what items we have.

**Comment by xxMUROxx** [comment]
@QuantumDeveloper any news? It would be cool if I could write code like this:

~~~xaml
<controls1:DropDownButton Content="..." >
  <controls1:DropDownButton.Items>
    <controls1:ToggleSwitch />
    <ComboBox />
  </controls1:DropDownButton.Items>
</controls1:DropDownButton>
~~~
otherwise I have to use the workaround with an Array:
~~~xaml
<controls1:DropDownButton Content="..." >
  <controls1:DropDownButton.Items>
    <x:Array Type="{x:Type system:Object}">
      <controls1:ToggleSwitch />
      <ComboBox />
    </x:Array>
  </controls1:DropDownButton.Items>
</controls1:DropDownButton>
~~~

**Comment by QuantumDeveloper** [comment]
Hi. The problem here is that actual Items property is to in corresponding with ContextMenu items property, which is actually displayed. Thats why there is an empty list.
Currently I have no idea how to fix that.
