### ISSUE TITLE
appbar icons won't show up when changing TransitioningContentControl's content

### ISSUE THREAD

**Issue by ShrewdSpirit** [MahApps/MahApps.Metro#2098]
Hi
I've an issue with changing TransitioningContentControl content. I've four user controls that have different appbar icons in a rectangle same as here http://mahapps.com/guides/icons-and-resources.html
When I change TransitioningContentControl's content to any of these user controls in any other event, their icons won't show up. But when I do it in constructor, I have the icons.
Sorry for my bad English xD

**Comment by Dotnetifier** [comment]
So you're using the MahApps.Metro.Resources icon pack, correct? And you have some icons that show up one one UserControl, but when you try to show those same icons on another UserControl they don't appear. Is that correct?

**Comment by ShrewdSpirit** [comment]
Yeah, thats right. The first UserControl's icon in a TransitioningContentControl is visible, but other UserControls in same TransitioningContentControl wont have any icons.

**Comment by Dotnetifier** [comment]
Had that problem too. The icons in the resource dictionaries are controls. They're also shared, meaning the resource system returns the same instance on every request. A control, however can only occur once in WPF's visual tree, so, the second time it tries to fit in the icon control it will fail because it is already present in the visual tree.

Add the [x:Shared="False"](https://msdn.microsoft.com/en-us/library/aa970778(v=vs.110).aspx) attribute to the icons you need in Icons.xaml (or do a Find/Replace and replace every <Canvas with <Canvas x:Shared="False").

**Comment by ShrewdSpirit** [comment]
That worked! Thank you so much. I had to forget about putting icons on UserControls, but now I can use them

**Comment by Dotnetifier** [comment]
You're welcome.

@punker76 You may close this one.
