### ISSUE TITLE
Blurry text during transition

### ISSUE THREAD

**Issue by void22** [MahApps/MahApps.Metro#2134]
Hi,

In 1.1.3-ALPHA texts are blurred during transition. This issue exist in lates 1.1.3-ALPHA174, but it happens in the past beta versions as well.
Some sample images from the demo application:
![blurrytext001](https://cloud.githubusercontent.com/assets/2505467/9914014/20c53d70-5cb0-11e5-885b-f324637d9bd0.gif)

![blurrytext002](https://cloud.githubusercontent.com/assets/2505467/9914022/273983f0-5cb0-11e5-9c7f-d47a02feb297.gif)

It happens under Windows 7 and Windows 10, with .NET4.5 and .NET4.6, both in Debug and Release builds. Affects almost all control which has animation (e.g.: clicking on Tile with text, dropping down ComboBox, etc.).
This issue did not exist in 1.1.2 release.
I was not able to fix this, so I would like to ask for your help.

Thank You.

**Comment by thoemmi** [comment]
I guess the blurriness during animation is caused by `TextOptions.TextFormattingMode="Display"`, but that was introduced almost 2 years ago (see dd57d33), For more information about `TextOptions.TextFormattingMode` see [this SO thread](http://stackoverflow.com/questions/190344/wpf-blurry-fonts-issue-solutions).

**Comment by void22** [comment]
Changing to `TextOptions.TextFormattingMode="Ideal"` was my first idea, but texts remain blurry. I suspect RenderTransform causing this.

**Comment by punker76** [comment]
@void22 This is not MahApps related stuff, it's WPF.... :-(
