### ISSUE TITLE
MetroWindow and MetroNavigationWindow don't inherit Page properties like WindowTitle, WindowHeight and WindowWidth.

### ISSUE THREAD

**Issue by neeooh** [MahApps/MahApps.Metro#2177]
Normally, Window and NavigationWindow inherit properties of Page, which allows me to dynamically set e.g. Window Title to whatever Page(or View) I am using.

I create **MetroWindow** which **contains a frame** hosting a page:

``` XAML
<Controls:MetroWindow x:Class="MyApp.Client.View.AuthenticationView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro">
    <Frame Name="ContentFrame" Source="LoginView.xaml"/>
</Controls:MetroWindow>
```

**Or MetroNavigationWindow**

``` C#
var navWin = new MetroNavigationWindow();
            navWin.Title = "Navigation Demo";
            navWin.Show();
            navWin.Navigate(new Uri("View/LoginView.xaml", UriKind.Relative));
```

Then the LoginView **Page**:

``` XAML
<Page x:Class="MyApp.Client.View.LoginView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MyApp.Client.View"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        WindowTitle="MyApp - Login" WindowHeight="300" WindowWidth="300">
```

Any idea how to fix this?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
