### ISSUE TITLE
DropdownButton ItemSource change

### ISSUE THREAD

**Issue by GAMP** [MahApps/MahApps.Metro#2181]
Hi i have this xaml where DropDownButton is bound to observable collection of items

            <ma:DropDownButton ButtonStyle="{StaticResource ChromelessButtonStyle}"
                                       x:Name="_host_groups"
                                       ArrowVisibility="Collapsed"
                                       BorderThickness="0"  
                                       ItemsSource="{Binding EntityLocator.HostGroups}"
                                       DisplayMemberPath="DisplayValue"
                                       Content="{lex:Loc Key=MOVE}" 
                                       Margin="2">
                    <ma:DropDownButton.ItemContainerStyle>
                        <Style TargetType="MenuItem" BasedOn="{StaticResource MetroMenuItem}">
                            <Setter Property="Command" Value="{Binding DataContext.MoveCommand,RelativeSource={RelativeSource AncestorType=ma:DropDownButton}}"/>
                            <Setter Property="CommandParameter" Value="{Binding Path=DataContext, RelativeSource={RelativeSource Self}}"/>
                        </Style>
                    </ma:DropDownButton.ItemContainerStyle>
                </ma:DropDownButton>
Each item Command is bound to property on DropDwonButton DataContext.
What i want to do here is to call a command on each menu item and pass its own DatContext as parameter. Everything works as expected as long as DropDownButton ItemSource does not change, once its changes the child menu items no longer has access to parent DataContext and i get this output 

System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MahApps.Metro.Controls.DropDownButton', AncestorLevel='1''. BindingExpression:Path=DataContext.MoveCommand; DataItem=null; target element is 'MenuItem' (Name=''); target property is 'Command' (type 'ICommand')

Does anybody has any idea what might be wrong here?

**Comment by GAMP** [comment]
Ok i found the problem. It seems that some of the styles was affecting the behavior. Not sure which one context menu or menu but without styles being referenced it works as it should.

**Comment by barbeque** [comment]
I am having a similar problem, though my `ItemContainerStyle` is not based on any other style and I am styling the entire `DropDownButton` instead of using the `ButtonStyle` property.

The first time I open the menu works properly; all commands are bound.

If I add anything to the collection backing the menu, I immediately get a console error about not being able to satisfy the binding. I have also tried using `ElementName` instead of `RelativeSource` to find the command, but that breaks in a similar fashion.

Once the menu has been opened, adding any items to the collection (including refreshing the collection from its data source) causes the same error to emerge for each new item.

Removing any `Style` or `ButtonStyle` overrides on the `DropDownButton` does not fix the problem. In order to verify that it was not one of my style modifications getting picked up automatically, I created a new project that demonstrates the problem. You can find that repo [here](https://github.com/barbeque/DropDownButtonBindingBug) but the XAML is just as follows:

```
<mah:DropDownButton Content="Show Entity..."
                    ItemsSource="{Binding Stuff, UpdateSourceTrigger=PropertyChanged}"
                    DisplayMemberPath="Name">
    <mah:DropDownButton.ItemContainerStyle>
        <Style TargetType="MenuItem">
            <Setter Property="Command" 
                    Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type mah:DropDownButton}},Path=DataContext.ShowEntityCommand}"/>
            <Setter Property="CommandParameter" Value="{Binding}"/>
        </Style>
    </mah:DropDownButton.ItemContainerStyle>
</mah:DropDownButton>
```

Fails on both MahApps.Metro 1.2.4 and 1.3.0

**Comment by barbeque** [comment]
Update: setting `BindsDirectlyToSource` on the Command binding fixed the problem, though I do not yet know why.

**Comment by barbeque** [comment]
I think I have a reasonable fix, by trying to find the `ContextMenu` that houses the `MenuItem` and then using its `PlacementTarget` property in order to grab the `DataContext` from the `DropDownButton`.

```
<mah:DropDownButton DockPanel.Dock="Top" Content="Show Entity..."
                    ItemsSource="{Binding Stuff, UpdateSourceTrigger=PropertyChanged}"
                    DisplayMemberPath="Name" >
    <mah:DropDownButton.ItemContainerStyle>
        <Style TargetType="MenuItem" BasedOn="{StaticResource MetroMenuItem}">
            <Setter Property="Command" 
                    Value="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=ContextMenu}, Path=PlacementTarget.DataContext.ShowEntityCommand}"/>
            <Setter Property="CommandParameter" Value="{Binding}"/>
        </Style>
    </mah:DropDownButton.ItemContainerStyle>
</mah:DropDownButton>
```

**Comment by sm-g** [comment]
https://mahapps.com/docs/controls/dropdownbutton and sample app still have wrong code. It works only first time, if the view recreated (with same viewmodel instance), only `PlacementTarget`-binding works
