### ISSUE TITLE
Error messages in Console output

### ISSUE THREAD

**Issue by ThomasWeiss** [MahApps/MahApps.Metro#2240]
My project is a Console app that creates a `MetroWindow` (for some reasons, this app has to be a Console app).
Some error sometimes pops up in the Console; it seems pretty random and the one I'm getting a lot these days is:
````
err:[0xe84]:d3d:D:\tinderbox\add-4.3\src\VBox\Additions\WINNT\Graphics\Wine_new\wined3d\resource.c 218: Resource 04D3EBD0 is being unloaded while mapped.
````
which happens when I call `ShowDialog()` on an `OpenFileDialog`.

It doesn't seem to be a serious issue though as the app continues to work normally, but I'd like to know if there would be a way to prevent that log to appear in the Console.

**Comment by Dotnetifier** [comment]
I do not know what exactly your program is doing, but I don't think that this is a MahApps.Metro related issue. The OpenFileDialog is a standard Windows dialog, and the error on the console appears to be a Direct3D (`d3d`) error. I'm not certain if this is related to "wine" appearing in the path, because that would mean this is somehow virtualized in Wine.

**Comment by ThomasWeiss** [comment]
Thanks for your comment.
I know that the "core" issue doesn't come from MahApps (background: I run the app in VirtualBox with 3d acceleration enabled, so this is most probably some errors raised by the driver) but as I could not reproduce it without MahApps (a simple WPF app launched as a Console app), it thought the actual logging to the Console was done by MahApps.

I realise it's not a big deal and it's certainly not a show-stopper for me; feel free to close it if it doesn't sound relevant! Thanks
