### ISSUE TITLE
clean up, vs 2015, readme...

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#2350]
- [x] style XAML with [XAML Magic](https://github.com/grochocki/XamlMagic) (only once, but config will be added)
- [x] [Paket](https://fsprojects.github.io/Paket/index.html) instead NuGet
  - [x] for restoring packages
- [x] some minor changes to icon packs
- [x] update readme
- [x] delete old stuff
- [ ] syle C# with R# (config will be added)
- [x] create new showcase gif

PRs
- #2330

**Note**
- The source will be VS 2015 C# 6 (Pro and Community) ready
- I created an extra branch **dev-vc2013** for those who doesn't want to change, but no new feature will be added in this branch by me
- The demo will be now compiled and added on each relase
- I hope I don't snub anyone with this :see_no_evil: 

Closes #2270 Code Style (ReSharper)

![iconpacks](https://cloud.githubusercontent.com/assets/658431/13028849/7a25dbea-d27b-11e5-9059-0e672e5e2268.gif)

**Comment by CADbloke** [comment]
If you're going the R# settings route you may want to consider [editorconfig](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) and/or [Rebracer](https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58) for pricks like me who set tabs to 2 and do [stupid things with braces and code formatting when nobody is looking](https://github.com/CADbloke/CodeLinker/commit/2754e71620f7004cf8b303bfb7f1950badb51458).

If you consider Rebracer, I [dug out some xml that does indenting](https://gist.github.com/CADbloke/6206b1d4084a88473689). It might actually work. Or not.

**Comment by punker76** [comment]
@CADbloke `.editorconfig` is already added

**Comment by CADbloke** [comment]
Whups. I promise I'll get better at this ... eventually. :/

**Comment by punker76** [comment]
@CADbloke and by the way, this formatting will be done only this time for existing code.

**Comment by gigios** [comment]
I'm not sure if this is the correct location where post my problem, but it is related the latest release of sources and paket usage.
Probably the problem is related to my configuration, but I'm not sure.

After one month I have downloaded the new sources and installed the paket extension in the VS2015, open the solution and started the MetroDemo app (FW 4.0). No build error are present but at runtime I receive the exception: An exception of type 'System.TypeLoadException' occurred in mscorlib.dll but was not handled in user code.
The exception is raised in the TextBoxHelper at the line 74 (tb.SetValue(SpellCheck.IsEnabledProperty, true);) of the method UseSpellCheckContextMenuChanged.
If I start the 4.5 version of the demo all works fine.
For my project this is not a problem because I'm not using the SpellCheck context menu, but I'm using the framework 4.0 and I don't know if there are other possible problems.

**Comment by punker76** [comment]
@gigios -> https://github.com/MahApps/MahApps.Metro/issues/2398
