### ISSUE TITLE
Question: Changing font style for watermark

### ISSUE THREAD

**Issue by deejay220989** [MahApps/MahApps.Metro#2491]
Hi all,

I'm using TextBoxHelper Watermark, and I would like to change the style. I prefer my watermark to be les bold and italic. How can I do that?
## 
### Environment
- MahApps.Metro v1.2.4
- Windows 8
- Visual Studio 2015 Update 2
- .NET Framework 4.0

**Comment by punker76** [comment]
@deejay220989 This is currently not possible.

**Comment by deejay220989** [comment]
Thanks for the response :)

**Comment by Dotnetifier** [comment]
Well it *is* possible to change the font size of the floating watermark. The style for the floating watermark TextBlock is defined [here](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Styles/Controls.TextBlock.xaml#L7) and it uses `FloatingWatermarkFontSize` for the font size. You can override that resource value in your own code:

First add `xmlns:sys="clr-namespace:System;assembly=mscorlib"` as an attribute, then add the following to an element using the floating watermark or any panel containing those elements:
```
<FrameworkElement.Resources>
    <sys:Double x:Key="FloatingWatermarkFontSize">14</sys:Double>
</FrameworkElement.Resources>
```

A lot of things may be off since it isn't officially supported I guess, but the styles might be modified so that they can be used this way (or `ControlHelper.FloatingWatermarkStyle` should be added).

**Comment by punker76** [comment]
@deejay220989 With 1.6.0 you can now override all Watermarks with this style

```xaml
    <Style x:Key="MahApps.Metro.Styles.MetroWatermarkTextBlock"
           BasedOn="{StaticResource MetroTextBlock}"
           TargetType="{x:Type TextBlock}">
        <Setter Property="IsHitTestVisible" Value="False" />
        <Setter Property="Opacity" Value="0.6" />
    </Style>
```

**Comment by buba4ko** [comment]
test

**Comment by buba4ko** [comment]
I did this by workaround - set green foreground to the TextBox when the Text value is empty, which actually sets the foreground of the watermark :)
But I would be glad if there is a official solution.
Here is my code, in case someone needs it:

        <Style x:Key="MahApps.Metro.Styles.MetroWatermarkTextBlock" BasedOn="{StaticResource MetroTextBlock}" TargetType="{x:Type TextBlock}">
            <Setter Property="IsHitTestVisible" Value="False" />
            <Setter Property="Opacity" Value="0.5" />
        </Style>
        <Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource {x:Type TextBox}}">
            <Style.Triggers>
                <Trigger Property="Text" Value="">
                    <Setter Property="Foreground" Value="Green" />
                </Trigger>
            </Style.Triggers>
        </Style>
