### ISSUE TITLE
Are there any plans to support UWP for this?

### ISSUE THREAD

**Issue by jterry75** [MahApps/MahApps.Metro#2590]
(a question)

Are there any plans to support UWP style development? This is great for WPF and I really like the ability to have the styles predefined and consumable while dynamically user changeable. It seems like with minimal work this should also work on the UWP platform but I don't really know as I haven't delved in the deep yet.

Thanks!

**Comment by AdditionalPylons** [comment]
This isn't an official answer, but I'll just throw in my $0.02

1. UWP already has it's own Metro/Modern UI controls immediately available. Porting Mahapps.Metro would be redundant to some degree. 

2. I doubt that most of the Mahapps.Metro controls are touchscreen friendly (gestures etc).

3. A large portion of the Mahapps.Metro codebase is for drawing custom window chrome, which uses the Win32 API directly. I don't believe this is something available for UWP. Furthermore, the windowing system in UWP doesn't seem to be very powerful at all, evidenced by Microsoft Edge's really lame windowing and tab features. So that would leave us with only custom controls, emphasizing points 1 and 2.

4. I can't say for sure, but most of the controls defined in the XAML files would probably not be reusable in UWP.

So I think doing this would actually take a considerable of work - enough to the point where creating a whole new framework for UWP would make more sense.

**Comment by jterry75** [comment]
No worries. I can just build a styles repo as you suggested that is targeted directly to UWP. This solve the part I want without having to port all the other areas you mentioned (which is likely not possible from the UWA sandbox).

Thanks!
