### ISSUE TITLE
DropdownMenu alike VisualStudio credentials

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#2641]
I'm trying to re-style the Dropdown menu to be similar to:
![vs](https://cloud.githubusercontent.com/assets/165290/18396943/655f1e4a-769c-11e6-8c31-09b582419fdc.png)

Forget about the "credentials error box" :)

My attempted so far:

![mine](https://cloud.githubusercontent.com/assets/165290/18396969/7d32aa6e-769c-11e6-8135-52a8b6540e5e.png)

The first issue was the `MenuItem`'s "Icon Area", which this [answer](http://stackoverflow.com/a/17724242/1830639) helped me out.

The second issue, is that I couldn't override the `MenuItem` style, for instance, I don't want MouseOver effect. I tried to set Style.Triggers of ItemContainerStyle but it didn't work.

The other issue, you can see in the image: `Separator` is acting like a MenuItem.
This is because I'm binding `Dropdown`'s ItemsSource to an `IUserAction` interface, and depending on the actual class, I render a different template. For the `SeparatorUserAction` I'm using a `<Separator />` template.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
