### ISSUE TITLE
SplitButton/DropDownButton not behaving as expected

### ISSUE THREAD

**Issue by bernd70** [MahApps/MahApps.Metro#2749]
Hi,

to my understanding a split button is a button which can be pressed on the left part for the primary action and on the right part it can be dropped down (ilke a ContextMenu) for an arbitrary number of secondary actions.

But with the MahApps SplitButton the button does change its content to the selected.
And the DropDown Button just behaves like a ContextMenu and misses the Split part.

My expectation the control behaves like for example the bootstrap ([http://getbootstrap.com/components/#btn-dropdowns]) implementation. See Split Button DropDown here.

Maybe MahApps is just missing a SplitDropDownButton control :-)

Bernd

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
