### ISSUE TITLE
Suggestion new (controls HelperTextBox) component for filter

### ISSUE THREAD

**Issue by robertorp** [MahApps/MahApps.Metro#2765]
## What steps will reproduce this issue?
Not a problem is a suggestion
_Write problem description here_

### Expected outcome

_Write expected outcome here_
TextBox accept layout for filter and others utilities
image by  gmail
![sugestion](https://cloud.githubusercontent.com/assets/10251705/21220322/78fa4930-c29f-11e6-9c6a-9f872e4cb0f9.png)

--
### Environment

- MahApps.Metro __v?.?.?__
- Windows __??__
- Visual Studio __20xx__
- .NET Framework __?.?__

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
