### ISSUE TITLE
Button Border not Transparent when Focused.

### ISSUE THREAD

**Issue by feinstein** [MahApps/MahApps.Metro#2767]
## What steps will reproduce this issue?

Place a `Button` inside a Flyout with some backgound color (mine id Cobalt Accent). When the `Button` has Focus, it's possible to see some of the white background coming off the corners of the border:

![image](https://cloud.githubusercontent.com/assets/8120472/21253477/31690c6c-c346-11e6-9131-48582af0bb2f.png)

### Expected outcome

No white background on the corners.

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@feinstein This will be fixed in upcoming 1.4.0. The `ToggleButton` had the same issue and is now also fixed.

![image](https://cloud.githubusercontent.com/assets/658431/21260583/f0da60ba-c386-11e6-8f8a-96c4850d557d.png)

![image](https://cloud.githubusercontent.com/assets/658431/21260586/f34c310c-c386-11e6-85a3-ed629e6736ed.png)

![image](https://cloud.githubusercontent.com/assets/658431/21260587/f57efe28-c386-11e6-83c5-7638e46c5004.png)

**Comment by feinstein** [comment]
@punker76 will #2458 be fixed as well?

**Comment by punker76** [comment]
@feinstein No, cause this would be a visual breaking change

**Comment by punker76** [comment]
@feinstein And why fixing? It's not a bug, it's in this case a feature (IsKeyboardFocusWithin). If you don't like it (and for a workaround), create a copy and remove this lines.

**Comment by feinstein** [comment]
@punker76 oh, ok, I got the impression it was a clicked state and not a IsKeyboardFocusWithin state, I will close the other issue then.
