### ISSUE TITLE
Some Enhancements for NumericUpDown

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2783]
## What steps will reproduce this issue?

1) When someone edits and leaves the field empty (validation template error appear), by default it would have to show the configured minor number (if there is one)

2) If you change the value by keyboard, you can exceed the limit and when the control loses focus, it corrects it. Is it possible that when you reach the limit (major or minor) no longer enter more numbers and the default value is one of the configured?

3) Is it possible to just disable the textbox and can only modify the value using the arrows?

4) When I press enter after editing, the dotted line appears, as if I was focusing the control.

![1](https://cloud.githubusercontent.com/assets/11781418/21504851/0b475f76-cc41-11e6-8107-5fb6402b620b.JPG)

### Environment

- MahApps.Metro 1.4.0
- Windows 7
- Visual Studio 2015
- .NET Framework 4.0

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
