### ISSUE TITLE
3D effects in tiles in xaml

### ISSUE THREAD

**Issue by Sneha-123** [MahApps/MahApps.Metro#2808]
I am using MahApps.metro for creating tiles in wpf xaml but I need these tiles to give a 3D effect.

Can anyone provide me piece of code for 3D effects on these tiles.

My code is:

```xaml
<controls:Tile TiltFactor="2"
			   Background="Transparent"
			   Foreground="White"
			   Grid.Row="1"
			   Grid.Column="1"
			   Width="{Binding TileWidth,UpdateSourceTrigger=PropertyChanged}"
			   Height="{Binding TileHeight,UpdateSourceTrigger=PropertyChanged}"
			   controls:ControlsHelper.MouseOverBorderBrush="White"
			   ToolTip="Home"
			   Command="{Binding RestartCommand}"
			   BorderBrush="#FF0080FF"
			   BorderThickness="1">
                   
    <Grid Width="{Binding TileWidth,UpdateSourceTrigger=PropertyChanged}" Height="{Binding TileHeight,UpdateSourceTrigger=PropertyChanged}">
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="20"/>
        </Grid.RowDefinitions>
        <Grid Grid.Row="0"
              Width="{Binding IconWidth,UpdateSourceTrigger=PropertyChanged}"
              Height="{Binding IconHeight,UpdateSourceTrigger=PropertyChanged}"
              HorizontalAlignment="Stretch"
              VerticalAlignment="Stretch">
            <Grid.Background>
                <ImageBrush ImageSource="../Images/home.png"/>
            </Grid.Background>
        </Grid>
        <TextBlock Grid.Row="1"
                   HorizontalAlignment="Center"
                   VerticalAlignment="Bottom"
                   FontSize="16"
                   Foreground="#FF0080FF"
                   FontWeight="Bold"
                   Margin="0,0,0,5">
                <Run Text="Home"/>
        </TextBlock>
    </Grid>
</controls:Tile>
```

### Environment
- Windows 10
- Visual Studio 2015

**Comment by Malavos** [comment]
What kind of effect are you looking for? (I know this is old, but...)

[With a little bit of help from some effects](https://www.codeproject.com/Articles/15231/WPF-tutorial-use-reflections-shadows-and-rotations), some effects can be done. But we need to understand what kind of effects we want to recreate. If it's just depth, you can do it following the link I've provided.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
