### ISSUE TITLE
DatePicker throws Exception

### ISSUE THREAD

**Issue by p3root** [MahApps/MahApps.Metro#2818]
## What steps will reproduce this issue?

Use DatePicker

### Expected outcome

That I have an DatePicker

--
### Environment

- MahApps.Metro __v1.4.1__
- Windows __10__
- Visual Studio __2015
- .NET Framework __4.6.1__

### Error

DatePicker throws exception:
{"Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception."}
{"Cannot add instance of type 'DatePickerTextBoxBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed."}

### Using

 <DatePicker/>

**Comment by punker76** [comment]
@p3root Can you create a short app which reproduces this error? thx

**Comment by p3root** [comment]
[WpfApplication1.zip](https://github.com/MahApps/MahApps.Metro/files/734825/WpfApplication1.zip),

It's a plugin based Application. I know that in there shouldn't be all depending libs in the plugin folder, but the error occures when the mahapps.metro.dll gets loaded a second time.

**Comment by punker76** [comment]
@p3root thx for the sample. the problem is that the mahapps dll is already loaded in the current domain. try the following code which should work...

```csharp
private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
    string directory = Path.Combine(AssemblyDirectory, "Plugins");
    if (!Directory.Exists(directory))
        return;
    string[] reports = Directory.GetFiles(directory, "*.dll");

    var currentAssemblyNames = new HashSet<string>(AppDomain.CurrentDomain.GetAssemblies().Select(a => a.GetName().Name));
    foreach (string report in reports)
    {
        var assemblyName = Path.GetFileNameWithoutExtension(report);
        if (!currentAssemblyNames.Contains(assemblyName))
        {
            Assembly ass = Assembly.LoadFrom(report);
            var types = ass.GetTypes().Where(p => typeof(IPlugin).IsAssignableFrom(p));
        }
    }

    new Window2().ShowDialog();
}
```

**Comment by p3root** [comment]
@punker76 Thanks, but I changed it that only the plugin assemblies are located in the plugin folder.

But anyway, why does the crash occure when loading the assembly twice?

**Comment by punker76** [comment]
@p3root your zip contains the mahapps dlls also at plugins folder

![2017-01-27_11h03_39](https://cloud.githubusercontent.com/assets/658431/22367158/633451b0-e480-11e6-821f-b27f86946de7.png)

**Comment by p3root** [comment]
@punker76 : I know, to demonstrate the issue. I changed it as I found out that this makes problems.

**Comment by punker76** [comment]
@p3root loading a assembly twice is not good, as you see ;-)

**Comment by SmithsonianDSP** [comment]
I started running into a similar problem, except that it wasn't throwing an exception during runtime; for me, it was throwing an exception in the designer and would only load a red error icon in place of the DatePicker control in the Designer preview, 

This thread was one of the first results that Google returned (and the one that seemed most relevant) to the problem I was having, however, I _**wasn't**_ loading an assembly twice so it didn't really help solve my problem.

So, having now figured it out, I just want to add a comment here in case anyone else experiences the same problem and end up here looking for a solution:

---

It turned out that the problem for me was being caused by having:
 
     <ResourceDictionary.MergedDictionaries>
         <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
      ....
 
Defined in my `App.xaml` _**and**_ having that included in another XAML resource dictionary that was also listed and included in the `App.xaml`'s `MergedDictionaries`. (So, in way, it kind of _was_ referencing/loading an assembly twice, but just not as obvious.)
 
I had a bit of trouble pinning this down because I simply didn't remember doing this, there (but I obviously must have...) and didn't actually catch it until looking at the Resources window in Blend and seeing another **`Linked to:`**` Controls.xaml` listed under that XAML resource.

After ensuring that there were no other duplicate/unnecessary resource references in any of my linked secondary Resource dictionaries, the problem disappeared and the DatePicker began to show/load in the designer correctly, again. 

---

Hopefully this will help anyone else who manages to make the same mistake and ends up here.

**Comment by sekulicb** [comment]
Hi. I have exactly the same problem as @SmithsonianDSP , but how to style multiple controls then. Lets say I have a style for MetroWindow and TabControl. In both cases I need a reference to **xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"**

What would be the solution here?

**Comment by timunie** [comment]
Hi @sekulicb 
normally this should not be a problem. If you want help about the usage please join us on gitter: https://gitter.im/MahApps/MahApps.Metro .

Happy coding
Tim
