### ISSUE TITLE
NumericUpDown Decimal Wrong Behaviour

### ISSUE THREAD

**Issue by MurariAlex** [MahApps/MahApps.Metro#2923]
## What steps will reproduce this issue?
In the metro demo, texts tab, numericUpDown section, enable HasDecimals, click and keep pressed the plus button of the numeric up down under the CultureInfo dropdown until the "Stringformat, Real Value" fields gets an strange value.
Disable the HasDecimal flag, the plus button doesn't work anymore, and I don't know if the strange value is a bug itself.

![image](https://cloud.githubusercontent.com/assets/11204378/25025400/7a55cdfe-2078-11e7-8a03-6b231b67600c.png)

### Expected outcome

The NumericUpDown should keep working even after disabling the HasDecimals flag.
Maybe the value of the "Stringformat, Real Value"  is wrong.

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@MurariAlex This is caused by using `double?` for the Value. If you click the up or down button the Value is increased or decreased by 0.1 in this sample. A double uses floating-point arithmetic, which is approximate but more efficient, but produces e.g this `5.1 + 0.1 = 5.1999999999999993`. For exact (human) values the decimal type must be used, which is a breaking change for this control.

Add. info http://stackoverflow.com/a/1165788/920384, http://stackoverflow.com/a/618596/920384, http://net-informations.com/q/faq/float.html

/cc @xxMUROxx
