### ISSUE TITLE
[Request]Win 10 Creators Update Hamburger Menu

### ISSUE THREAD

**Issue by MurariAlex** [MahApps/MahApps.Metro#2931]
The new Win 10 hamburger menu style that came with Creators Update looks really cool too, this was taken from the new Windows Defender window.
The selection style is the difference, the foreground color of the icon and font changes, and there's the sidebar on the left of the icon.

Maybe we could have this style in MahApps. 

![image](https://cloud.githubusercontent.com/assets/11204378/25134518/27b99e8e-2426-11e7-8f36-7fc52bd67037.png)

Thanks,

**Comment by amkuchta** [comment]
This is gorgeous, but I also like the ability to use the style that @punker76 created - perhaps this could be an option (e.g. `Style="{StaticResource CreatorsUpdateStyle}"), with the style being bound by default to the MahApps standard?  (This would mean moving the style for the MahApps standard to its own resource and either modifying the template to allow for the highlighting on the sidebar or creating a new template altogether)

**Comment by amkuchta** [comment]
@punker76 I'm gonna take a swing at this one (dunno if you can assign it to me or not)

**Comment by amkuchta** [comment]
I'm taking a swing at this.  Wish me luck.

**Comment by amkuchta** [comment]
I've got the core requirement for this fully implemented (PR to follow this evening).  One of the things that I don't like is that the header over the content area is not there by default. I could build it into the template and make it so that users can bind their label (or whatever) to the title text, which would make the control easier to use but also breaks from how it is done in the UWP toolkit.  On the plus side, it would also allow me to set a style for the title bar that follows the rest of the control, preventing the users from having to set it manually. @punker76, thoughts?

**Comment by amkuchta** [comment]
Boom.
![resizedcreatorsmenudemo](https://cloud.githubusercontent.com/assets/6255186/26367092/7570bb70-3fbb-11e7-92f4-af1b813b300b.gif)
