### ISSUE TITLE
NumericUpDown snap to interval

### ISSUE THREAD

**Issue by seb30** [MahApps/MahApps.Metro#2952]
It would be nice, if the value in a `NumericUpDown` snaps to the interval (manually entered and/or changed by the buttons).

- MahApps.Metro v1.5.0
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.6.2

**Comment by punker76** [comment]
@xxMUROxx WDYT?

**Comment by xxMUROxx** [comment]
@punker76 

The idea is nice.

There are two concerns:

- This feature can only work if the `Value` is "adjusted" to the interval on `LostFocus`; otherwise the value is changed at any key stoke.
- The interval is 5 and the value entered is 4. To what value should 4 be "adjusted" 5 or 0? (I am no fan of introducing a `SnapDirection` property)

**Comment by seb30** [comment]
> The interval is 5 and the value entered is 4. To what value should 4 be "adjusted" 5 or 0? (I am no fan of introducing a SnapDirection property)

In my opinion it should snap to 5 (or to the maximum). I've done the calculation in the past with `Math.Round(value / interval) * interval`.

**Comment by xxMUROxx** [comment]
@seb30 According your code you suggest to round to the "nearest possible interval"?

**Comment by seb30** [comment]
Yes.

**Comment by xxMUROxx** [comment]
@punker76 I will implement a demo, then we can decide if this feature suits to the library.

**Comment by seb30** [comment]
Works great (for my needs, which I've tested)!
