### ISSUE TITLE
Mahapps window steals focus

### ISSUE THREAD

**Issue by bardospeter** [MahApps/MahApps.Metro#2996]
## What is the issue?

MahApps window sometimes steals focus in our application. As it turned out, it can steal the focus in the official test app as well:

[Reproduction video](https://drive.google.com/open?id=0B-visWMOSK_xSjdMbGNSdHNHZkk)

## What steps will reproduce this issue?

1. Start MahApps.Metro.Demo.NET45
2. Click on VS button
3. Go back to main window
4. Maximize
5. Minimize
6. Maximize back from taskbar (click on main window on taskbar)

Now it steals focus

### Expected outcome

It should not steal the focus

### Environment

- MahApps.Metro: 1.5.0.0.
- Windows OS: Windows 10 creators update
- Visual Studio 2017
- .NET Framework 4.5

**Comment by bardospeter** [comment]
Sorry, made the link public now

**Comment by JerryJian** [comment]
I encountered a lost-focus problem when I launch a metro window as dialog window (new MetroWindow().ShowDialog()). I remove GlowWindowBehavior in my metro window style.   
Because I found that it will create 4 windows around the main window in order to implement shadow effect, and sometimes one of them will capture the focus. You can try to custom metro window style and remove GlowWindowBehavior.  

[GlowWindowBehavior here](https://github.com/MahApps/MahApps.Metro/blob/master/src/MahApps.Metro/MahApps.Metro/Themes/MetroWindow.xaml#L572)

**Comment by punker76** [comment]
@bardospeter @JerryJian This is fixed now and will be available in 1.6.0 (also available in latest pre-release)
