### ISSUE TITLE
Datagrid - grouped items are not directly below column header.

### ISSUE THREAD

**Issue by Krzychu87** [MahApps/MahApps.Metro#3011]
Like in the title - grouped items in datagrid are not directly below column header (I use ICollectionView as data source).

![image](https://user-images.githubusercontent.com/30173721/28209352-78155f52-6892-11e7-85e1-65fa0dd9a66b.png)

- MahApps.Metro V1.5.0.23
- Windows 7
- Visual Studio Professional 2015
- .NET Framework 4.5.2

I tried so hard to upload my demo to GitHub, but with no success... :/

**Comment by punker76** [comment]
@Krzychu87 I figured it out that this is caused by the Expander style. I'll fix this.

**Comment by punker76** [comment]
@Krzychu87 Can you popst your Xml in here? or provide a zip file with your sample?

**Comment by punker76** [comment]
@Krzychu87 It looks like this is caused by the group style itself...

**Comment by MurariAlex** [comment]
It´s tricky, because we can have multiple levels of grouping (right?):

--00000
---11111
----22222

So the column header on the top will never really match all groups of items.
Some paid frameworks includes an header for each level of grouping

![image](https://user-images.githubusercontent.com/11204378/30481655-410be1da-99f6-11e7-9dcb-b89363b95480.png)

I this scenario I can´t really think of another solution.
