### ISSUE TITLE
Should we drop the .Net 4 support?

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3041]
You know MahApps.Metro comes with .Net 4 and .Net 4.5, but it was always been laborious.

So should we

👍 drop this
👎 leave this

.Net 4 support?

IMO I think this can be dropped...

Thx

**Comment by feinstein** [comment]
👍 drop it, but mark the lastest version with .NET 4.0 support with a tag, so if anyone needs it, he can easily use it.

**Comment by amkuchta** [comment]
I agree. Drop it, but tag the last 4 release.

**Comment by thoemmi** [comment]
Microsoft's support for .NET 4, 4.5, and 4.5.1 ended January 12, 2016 ([Source](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/)). That's almost 20 month ago. Therefore I'd say drop it.

**Comment by thoemmi** [comment]
BTW, there are still requests for [Windows XP support](https://github.com/MahApps/MahApps.Metro/issues?utf8=%E2%9C%93&q=label%3A%22XP%20is%20dead...%22) coming, so tagging the last .NET 4 version would be relieving. 🙄

**Comment by jogibear9988** [comment]
increase the major when you drop support...

**Comment by punker76** [comment]
@jogibear9988 Yes, v1.6.0 will be the last version with .Net 4.0 support. So v2.0 will drop this... that's the plan.

**Comment by ShannonZ** [comment]
Drop it. Don't make large library to implement compatibility.

**Comment by ghiboz** [comment]
Drop it! 👍

**Comment by Nuklon** [comment]
Please keep it, it's the only .NET available on XP. There's hardly a need to drop it as long as it's working as-is.

**Comment by punker76** [comment]
@Nuklon I'll tag/branch this after 1.6.0 with last dotNet4, but I'll not update this branch any further.

**Comment by Nuklon** [comment]
There's no code specific to .NET 4.0 as far as I can find? It'd be a shame to drop support for it if that means we'd have to compile it to .NET 4.0 ourselves. Especially when you can just keep it as-is.

**Comment by punker76** [comment]
@Nuklon All async stuff is special handled, there is also a NET4 compiler directive. ControlzEx handles .NET 4 too. Virtualization in styles is special handled and makes it difficult to handle for net 4.5+ I don't think that this would be a shame...

**Comment by Nuklon** [comment]
Still, .NET 4.0 is the only thing supported on XP (yes, there are people still using it). I know that it's not much cared for anymore but certain markets still use it quite a lot (Asia for example).

**Comment by batzen** [comment]
XP also isn't supported anymore.
Supporting libs on unsupported OS/Framework requires time and does not make a lot of sense IMHO.
If anyone needs it they can vote here to keep it.

**Comment by thoemmi** [comment]
MahApps.Metro doesn't support Windows XP anymore for quite some time.

**Comment by Nuklon** [comment]
It's working on XP here :)

**Comment by thoemmi** [comment]
@Nuklon It *may* work for you, but it's not supported. There are [several issues reported related to Windows XP](https://github.com/MahApps/MahApps.Metro/issues?utf8=%E2%9C%93&q=label%3A%22XP%20is%20dead...%22), but they won't get fixed.

Anyway, the discussion is not about Windows XP but .NET 4.

**Comment by alexeygritsenko** [comment]
Hi, this is a very stupid thing! Please do not remove .Net 4.0 support. My program must necessarily work with Windows XP. If you delete something I can not get updates this is bad

**Comment by jenokizm** [comment]
Please do not delete it!

**Comment by punker76** [comment]
@alexeygritsenko @jenokizm Nothing will be delete. The v1.6.0 will be the last version with .Net 4, after this there will be a branch alive which has this in, but it will not be update from me. Feel free to do this and create a PR for this with the latest changes from the upcoming 2.0+

**Comment by Bykiev** [comment]
@punker76, I think you should continue to support a .NET 4.0 version: no more new features but still fix the bugs

**Comment by batzen** [comment]
@Bykiev he will create a tag in git. But i don't think he will fix bugs there. IMHO he shouldn't fix bugs there. Would you fix bugs in software you don't use and don't get paid to work on?

**Comment by Bykiev** [comment]
@batzen, of course, no need to support a dead software, but .NET 4.0 isn't dead, at work, we continue support our software because there is some Windows XP PCs still working even Microsoft dropped it's support.

**Comment by batzen** [comment]
@Bykiev .NET 4.0 and Windows XP are dead and shouldn't be used anymore. Still running Windows XP today is kinda insane from a security point of view.

And you didn't answer my question...

**Comment by feinstein** [comment]
@batsen, the whole point of open source software is to support the community, not being paid or only fixing what you use.

I agree that supporting windows XP is insane on a technological standpoint, but there are lots of industries still using it and not supporting those clients is insane in a financial standpoint.

**Comment by batzen** [comment]
@feinstein Everyone in the world of OSS is free to only fix what he/she likes to fix. That's OSS.

If you demand someone to fix/maintain something for you because it would be insane in a financial standpoint then you obviously should bring some of that financial standpoint to the table, or even better contribute and fix it yourself.

**Comment by feinstein** [comment]
@batzen, I think you misunderstood my point, I was speaking about 2 separate things.

I personally don't think we should continue to support .NET 4.0 here, but your statement of only supporting thing that we use and care about its not my personal opinion on software quality. This can easily lead to code that looks like Swiss cheese, lots of good cheeses and still lots of holes. 

My comments on Windows XP was just to make a statement on why people still support it, even been a security nightmare. And yes, I believe companies that need that support could help financially, so that old code that they need can still be supported, but I didn't want to tie those 2 subjects together.

**Comment by batzen** [comment]
@feinstein My initial question to the other guy was like "would you deliver what you demand from others?". Getting no answer to that is enough of an answer.

So you maintain an OSS project where you showcase your opinion about software quality and swiss cheese?

**Comment by feinstein** [comment]
@batsen I don't understand your question.

Anyway, anyone interested in the whole .NET 4.0 debate should read the beginning of this thread, where it's clear it won't be supported anymore and only have a tag. 

No need to further discuss philosophies here, cluttering people's emails.

**Comment by Bykiev** [comment]
@batzen, sorry for a long delay, I'm in a different time zone....
I don't understand your question too. Of course, at work I'll not support software which isn't used by anyone. But it's an open source framework, and if community is using it there is no any reasone to not fixing bugs. 
I agree with @feinstein, if @punker76 decided to not suppport it on .NET 4.0 we can't do anything except to make own PRs.

**Comment by jogibear9988** [comment]
I don‘t see the Problem here. I don‘t think there are many bugs, or no one of you had used it. So, droppibg support doesn‘t mean to delete it. 
As there are no changes in Net 4.0 any more (cause Ms droppef support), your app using this lib will work as before, and you lived with bugs of the lib (if there were any) since months, so why shouldn‘t work for months again.
And if it will not because the bug is really critical, I‘m sure plunker (or some other contributor) will help!

**Comment by jenokizm** [comment]
Hi guys. Perhaps in some kind of fictional magic world, Windows XP are obsolete and no longer use, but in reality they are often found in other areas. You can look at this question on the other hand, the support of .Net 4.0 allows you to run the application on computers with Windows 7 because this version is on the system by default, and some users are lazy to update .Net.

**Comment by Malavos** [comment]
@jenokizm  that's just my opinion, but if you're making a app for someone with XP, you better off using classic WF. You will have some troubles with wpf beyond MahApps on XP. Not to mention the poor perfomance of some libraries and other content.


While I don't *personally* agree that we should drop 4.0, the *commercial* and *logical* standpoint is that we drop it. If Microsoft dropped it, we should not move forward with it. It will free us to develop, fix and try new things out, without "looking back".

That's just my viewpoint. That's why I voted in favor to drop it.

**Comment by sbrian26** [comment]
Drop
