### ISSUE TITLE
TabControl & Scroll

### ISSUE THREAD

**Issue by LiptonOlolo** [MahApps/MahApps.Metro#3099]
Hello!
There's been a problem that there's no Scroll in TabControl.
To appear in the normal TabControl, you must write the following: 
```C#
<Grid.Resources>
 <ResourceDictionary source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml"/>
</Grid.Resources>
```
But he's not going to appear for Metrotabcontrol, etc.
Pls Fix it.

### Environment

- MahApps.Metro __v1.5.0.23__
- Windows OS __7__
- Visual Studio __2017__
- .NET Framework __4.6__

_Sorry for my bad English, I'm from Russia_

**Comment by punker76** [comment]
@LiptonOlolo Yes, this is by design. The `MetroAnimatedSingleRowTabControl` has a different style to the one which is in `Controls.AnimatedSingleRowTabControl.xaml`.

![2017-11-14_11h48_23](https://user-images.githubusercontent.com/658431/32776088-c3cb7b5c-c931-11e7-9c65-d3450822e8a9.png)

![2017-11-14_11h48_32](https://user-images.githubusercontent.com/658431/32776089-c3e908b6-c931-11e7-991e-f905d5ae1c8e.png)
