### ISSUE TITLE
ContextMenu - TemplateBinding BorderBrush for SubMenu?

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#3102]
Would be great to inherit the BorderBrush for the subitem...

![image](https://user-images.githubusercontent.com/16019165/32666077-a2347654-c636-11e7-968a-8f8173eaeebf.png)

To 
![image](https://user-images.githubusercontent.com/16019165/32666002-623417f8-c636-11e7-8caa-08c596979e64.png)

https://github.com/MahApps/MahApps.Metro/blob/cc75ce8e10075abffdfc5c6a62ff79eb24508954/src/MahApps.Metro/MahApps.Metro/Styles/Controls.ContextMenu.xaml#L289

## Workaround
Override the x:Key

`<SolidColorBrush x:Key="SubMenuBorderBrush" Color="{DynamicResource Gray8}" />`

![image](https://user-images.githubusercontent.com/16019165/32665926-20f17128-c636-11e7-8aad-61e6f3d3aec8.png)

### Environment

- MahApps.Metro __v1.6.?__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.6__

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
