### ISSUE TITLE
MetroWindow in NVIDIA surround mode corrupted

### ISSUE THREAD

**Issue by AlexBolotsin** [MahApps/MahApps.Metro#3157]
Good day,

I've noticed a bug with the Demo application which leads to view corruption in major way.

Steps:
1. Setup Surround mode with at least 2 monitors connected to the machine.
2. Run demo application.

After doing so - you will see that the window tried to maximize to 2 monitors and got only a half visible.

I expected that the window to have MS window behavior - maximize to one or another monitor.

- MahApps.Metro __master__
- Windows OS __1703 15063.786__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@AlexBolotsin Can you try it again with `develop` version (pre-1.6.0)? thx

**Comment by AlexBolotsin** [comment]
For some reason basic WPF window doesn't have that behavior. I was wondering if you could have an idea or two on this topic.
That would help a lot if you would be able to give it a look.
In any case - thank you for lightning fast response 👍

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
