### ISSUE TITLE
Problems when FlowDirection is RightToLeft

### ISSUE THREAD

**Issue by ahmedflix25** [MahApps/MahApps.Metro#3184]
**Environment**

- MahApps.Metro 1.6.2
- Windows OS 10 April Update 64bit
- Visual Studio 2017 Community 15.7.1
- .NET Framework 4.7.1 

Using "Controls:TextBoxHelper.Watermark" with "NumericUpDown" the Watermark doesn't follow the HorizontalContentAlignment for the controller

![0xuux5i - imgur](https://user-images.githubusercontent.com/658431/45844276-39bc9c80-bd22-11e8-99d9-49f21dcbc39a.png)

![eellbeo - imgur](https://user-images.githubusercontent.com/658431/45844295-43de9b00-bd22-11e8-9f7c-f0230f16db37.png)

If the culture is ar-EG the "." (decimal point) and the "," show as empty square 

![thoezi8 - imgur](https://user-images.githubusercontent.com/658431/45844320-5658d480-bd22-11e8-920c-606aa5819d0c.png)

The problem is with the default font "Roboto" and Arabic
also i can't type a value as ".2", i have to type it like that "0.2"
you will need this system settings

![image](https://user-images.githubusercontent.com/658431/45844386-8b652700-bd22-11e8-82c6-737bc85d7d77.png)

![image](https://user-images.githubusercontent.com/658431/45844395-94ee8f00-bd22-11e8-9b9e-606457e253a5.png)

and for the controller itself Culture=ar-EG and FlowDirection=RightToLeft

Can't change the FlowDirection for individual Columns controllers like "DataGridCheckBoxColumn", "DataGridTextColumn" or "DataGridComboBoxColumn"

The check mark for the "DataGridCheckBoxColumn" shouldn't change it's direction even if the controller "FlowDirection" is set to "RightToLeft" only the text like the normal "CheckBox" controller

- DataGridCheckBoxColumn FlowDirection=RightToLeft
![idx0zjv - imgur](https://user-images.githubusercontent.com/658431/45844136-cdda3400-bd21-11e8-8fa8-e349ca11c979.png)

- Normal CheckBox FlowDirection=RightToLeft
![48wvqbx - imgur](https://user-images.githubusercontent.com/658431/45844168-e0546d80-bd21-11e8-8f3a-d6ad14de4e07.png)

- Normal CheckBox FlowDirection=LeftToRight
![h3gx7v4 - imgur](https://user-images.githubusercontent.com/658431/45844183-eb0f0280-bd21-11e8-87e8-10e8cbcfcbf2.png)

thanks

**Comment by ahmedflix25** [comment]
?!!!!!!!!!!!!!!

**Comment by ahmedflix25** [comment]
updated

**Comment by ahmedflix25** [comment]
updated

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏

**Comment by ahmedflix25** [comment]
i will look into them again

**Comment by ahmedflix25** [comment]
they have been fixed i tried the demo app with the same settings from the latest commit 👍.
