### ISSUE TITLE
WindowTitleBrush set in WindowBackgroundBrush in BaseLight theme problem

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3194]
At first I thought that it should be so, until I tried the dark theme.

I make a simple window:

![screenshot_1](https://user-images.githubusercontent.com/12638819/36469921-052ef86a-16fa-11e8-98d1-4cb6694ebbc0.png)

Next - set the value **WindowTitleBrush="{DynamicResource WindowBackgroundBrush}"** and get this result:

![screenshot_2](https://user-images.githubusercontent.com/12638819/36469966-334c632c-16fa-11e8-8129-8e59510733c2.png)

However, if I change the theme to BaseDark, everything looks normal:

![screenshot_3](https://user-images.githubusercontent.com/12638819/36469996-50e0f402-16fa-11e8-8758-537b375ebdba.png)

### Environment

- MahApps.Metro __v1.6.0__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@Pekshev The `TitleForeground` is set to `IdealForegroundColorBrush` by default. So if you want the correct foreground, then set the `TitleForeGround` to `{x:Null}` or whatever you want. The `IdealForegroundColorBrush` is also set as Foreground for `WindowButtonCommands` and the `WindowCommands`.

I will look for a better way and fix this...

**Comment by Pekshev** [comment]
The problem is that the **IdealForegroundColor** always set to **White**

**Comment by punker76** [comment]
@Pekshev It's not always white, only for the accent colors where white is the best (e.g. for yellow it's black)

**Comment by Pekshev** [comment]
@punker76 
except for the white color =))

**Comment by punker76** [comment]
@Pekshev the `IdealForegroundColorBrush` is related to the accent color! So the bug itself is not there is more at the `WindowButtonCommands` and `WindowCommands` style. I will fix this there.

**Comment by Pekshev** [comment]
So far I solved the problem so
```xml
<ResourceDictionary.MergedDictionaries>
    <!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
    <!-- Accent and AppTheme setting -->
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />
</ResourceDictionary.MergedDictionaries>
<SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{StaticResource BlackColor}" options:Freeze="True" />
<SolidColorBrush x:Key="IdealForegroundDisabledBrush" Opacity="0.4" Color="{StaticResource BlackColor}" options:Freeze="True" />
```

**Comment by Pekshev** [comment]
Unfortunately, when i change the theme through them manager, the brushes change. I'll wait for the bugfix

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

I tested this issue again with the following property values:

```
WindowTitleBrush="{DynamicResource WindowBackgroundBrush}"
NonActiveWindowTitleBrush="{DynamicResource WindowBackgroundBrush}"
TitleForeground="Transparent"
```

I notice that the trick is to set the TitleForeground to Transparent.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
