### ISSUE TITLE
Cannot programmatically maximize window.

### ISSUE THREAD

**Issue by MairwunNx** [MahApps/MahApps.Metro#3287]
**Describe the bug**
This mistake was sort of decided, but I still have to this day. Why the window can not open to maximum without `ResizeMode = ResizeMode.NoResize;` This is not the best workaround.

In xaml, I have SaveWindowPosition = "True", and when the user extends the window to the maximum and exits the application the next time application can't start, more precisely the program is launched, but it needs to be minimized and maximized in the task manager. (Video).

I solved some of the problem with this code:

```
            if (WindowState! = WindowState.Maximized)
            {
                ResizeMode = ResizeMode.NoResize;
                IsWindowDraggable = false;
                WindowState = WindowState.Maximized;
            }
            else
            {
                ResizeMode = ResizeMode.CanResize;
                IsWindowDraggable = true;
                WindowState = WindowState.Normal;
            }
```

But it does not help while loading, I know about the `ResizeMode method = ResizeMode.NoResize ;`, but it does not fit, I want my program to be changed in size, I tried to set `ResizeMode.CanResize;` in the Loaded event, but it did not help and led to the case that was shown on the video above.

**To Reproduce**
1. Go to 'MainWindow.xaml'
2. Paste SaveWindowPosition="True" in mah:MetroWindow ...
3. Compile application and expand application to maximize.
4. Restart app and see error :)

**Expected behavior**
Normal behavior when expanding the window to a maximum without extra code.

**Video**
https://www.youtube.com/watch?v=UJzcSM9nv1Y&feature=youtu.be (0:28)

**Environment**
 - MahApps.Metro version [v1.6.5]
 - OS: [Win10 1803]
 - Visual Studio [2017 15.7.5]
 - .NET Framework [4.7.1]

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
