### ISSUE TITLE
IsEnabled does not work properly on HamburgerMenuItem

### ISSUE THREAD

**Issue by igorquintaes** [MahApps/MahApps.Metro#3293]
**Bug Description**
Is not possible to enable or disable a _HamburgerMenuItem_ inside a .xaml file. 
If a *HamburgerMenuItem* contains an _IsEnabled_ attribute, does not matter if it is True or False, binded value or not - it always shows as disabled.

**To Reproduce**
Based on [punker76/code-samples](https://github.com/punker76/code-samples):
1. Open HamburgerMenuApp.V2
2. Find a _HamburgerMenuGlyphItem_ in MainWindow.xaml
3. Add _IsEnabled="True"_

**Expected behavior**
Menu item should still be enabled.

**Environment(please complete the following information):**
Based on [punker76/code-samples](https://github.com/punker76/code-samples):
- OS: Win10 1803
- VS 2017 15.7.3

Based on my own code:
- MahApps.Metro updated
- OS: Win10 1803
- VS 2017 15.7.3
- .NET Framework 4.5

**Repo**
Since it can be simulated on [punker76/code-samples](https://github.com/punker76/code-samples), i think it is not needed.

**Additional context**
Based on Issue #2865, and Pull Request #2921 it is expected to work.

**Comment by realivanjx** [comment]
same here. i changed IsEnabled via C# code but if i disabled a menuitem then i cant enable it again using IsEnabled = True :(

**Comment by Anapher** [comment]
I don't think that this is solved as I just cloned the current develop branch and the problem is still there. I'm pretty sure that the problem is caused [by this line](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs#L261). In this [void](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs#L243), `CanExecute` is set to `true` if the `Command` is `null`. The problem is, that on creation the `Command` is `null` but `CanExecute` is `false` which is a wrong state. I will submit a PR that changes [this line](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs#L264) to ` private bool canExecute = true;`

**Comment by Hanebu** [comment]
Im currently stuck on that IsEnabled thing. Is there any code example of how to enable and disable a menuitem in a hamburger menu?

**Comment by punker76** [comment]
@Hanebu If you use the v2.0 alpha then this property should work as expected.

**Comment by Hanebu** [comment]
Awesome, I will test this right now :-) Thanks!
