### ISSUE TITLE
How to reference resources like AccentColorBrush in the 2.0 prerelease?

### ISSUE THREAD

**Issue by rabejens** [MahApps/MahApps.Metro#3411]
I am using MahApps.Metro prerelease 2.0.0-alpha0170 but cannot figure out the namespace / path of things like `AccentColorBrush`.

Where is it?

**Comment by punker76** [comment]
@rabejens The accent and theme brushes will be now generated on every build. It's a breakin gchange, because they are now located at a different place. The [Wiki](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start#add-the-resources-in-appxaml-in-v20-breaking-change) is updated, documentation will come.

**Comment by rabejens** [comment]
I just see adding `Background="{DynamicResource AccentColorBrush}"` to e.g. a label works, it compiles and runs but I get a blue squiggly in the WPF designer. How do I make that go away?
