### ISSUE TITLE
The provided dialog is not visible in the specified window.

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3451]
**Describe the bug**
Calling `DialogCoordinator.Instance.HideMetroDialogAsync` cause this exception after change window's theme or accent.

**To Reproduce**
1. Calling `DialogCoordinator.Instance.ShowMetroDialogAsync` to show a custom dialog.
2. Change theme or accent of the window that showing custom dialog.
3. Calling `DialogCoordinator.Instance.HideMetroDialogAsync` from the close button of dialog.
4. Occur this exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/4510984/52770630-95d7e280-306e-11e9-89d5-84a5fda31097.png)

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: Win10 1809
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
