### ISSUE TITLE
A Dialog not dependant of MetroWindow for PlugIn developments

### ISSUE THREAD

**Issue by jorgechoypernia** [MahApps/MahApps.Metro#3476]
Can we pop-up MahApps.Metro Dialog from a "class library project" without having MetroWindows screen?

It would be nice to have a Dialog control that is not dependant on MetroWindow. So it can be executed independent of its extension ShowMessageAsync.

Scenario:

 I developed a nice launcher application that executes actions or business logic from external plugIn or dlls. Developed plugIns can have custom business logic such as modifying registry of windows, create files, execute applications, and so other many others functionalities.
 
We are now in a position to develop a plugIn that will pop-up a confirmation dialog. However, this is not possible because the dll or plugIn developed does not have any MetroWindow windows to use the showMessage extension.

We end up displaying a traditional WinForm pop up dialog.

Thanks.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
