### ISSUE TITLE
Ability to set the gutter on CustomDialog

### ISSUE THREAD

**Issue by gnewtzie** [MahApps/MahApps.Metro#3484]
**Is your feature request related to a problem? Please describe.**
When showing a CustomDialog, I would like the ability to change the default gutter on the left and right of the content, so that i can show more content.
The existing implementation uses a fixed 25* grid column definition, hard coded in the CustomDialog template.
```
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="25*" />
                    <ColumnDefinition Width="50*" />
                    <ColumnDefinition Width="25*" />
                </Grid.ColumnDefinitions>
```

**Describe the solution you'd like**
I'd like to be able to set the width weighting for the gutter from the MetroDialogSettings when passing in to the .ShowMetroDialogAsync() method. Something more like:
```
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="{Binding GutterPercent}" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="{Binding GutterPercent}" />
                </Grid.ColumnDefinitions>
```

**Additional context**

**Closed Issues**

**Comment by Evangelink** [comment]
@punker76, do you have any preference between:

- keeping the current implementation with the 3 columns and binding the 2 outer ones to some property (as suggested by @gnewtzie)

- removing these 2 empty columns which only provide left/right margin and to let the user provide a margin to the middle column. This implies a fix margin instead of a scaling one as for the previous solution.

**Comment by Evangelink** [comment]
_FYI I have deleted my previous post_

We can actually handle this in quite a lot of ways: 

- Bind each margin to a `double` property which represents a percentage (ratio) and use a converter to transform this value into a `GridLength` and fix the middle column to `*`. The drawback of the `double` property is that the user can't define a fix margin (e.g. 300).

- Bind each margin directly to a `GridLength` property and fix the middle column to `*`.

- Fix the left and right columns to `*` and allow to bind the middle column width (again there is the question of using `double` or `GridLength`)

- Use some kind of enumeration for the left/right margin space like `NoMargin`, `SmallMargin`, `LargeMargin`, honestly I don't think that's a really good idea because we are putting a useless limit to the customization.

cc @punker76 

When the choice is made, I will happily create a PR for this.

**Comment by punker76** [comment]
@Evangelink https://github.com/MahApps/MahApps.Metro/pull/3518
