### ISSUE TITLE
Proper Windows 10 style

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3508]
Could we get a proper Windows 10 style please? Starting by fixing the checkbox style (requested more than two years ago, reported a couple of times by different people) over to a fluent style? It  currently doesn't really fit into Windows 10 at all. And although a visual change was kinda announced two years ago, nothing have changed.

I'm sorry for being the one idiot mentioning it but I think that many people would really appreciate if the style can be updated to the current standard. I know this is a free time project and such, so please consider this as a "nice way to ask for it pretty please" in case it doesn't sound like that. Thank you.

**Comment by timunie** [comment]
@Symbai you're not allone, i am waiting with you :-) . I think we have to be a bit more patient ;-). 

See also #3328 , #3326 , #3136

**Comment by batzen** [comment]
So you are already (at least) three (counting @Nuklon in) people who could take this as an opportunity to contribute to this open source project.
Looking forward to your PR (or PRs as it would probably be better to split this into multiple PRs).

**Comment by batzen** [comment]
@Symbai Why did you close this?

**Comment by Symbai** [comment]
Because of the negative feedback

**Comment by gep13** [comment]
@Symbai any negative feedback you received is likely due to the way in which you phrased the problem that you are seeing.  I know you say that you were trying to ask it nicely, but I, and obviously others didn’t think it came across that way.

A far better way to approach this would have been to ask “how can I help”, or “where would be a good place to start looking at testing/fixing this”?

Unless there is another issue in this repo specifically requesting this addition, I personally would suggest that it should be re-opened so that it can be tracked.

**Comment by timunie** [comment]
I really would like to help, but I am not a learned programmer.  So code produced by me might not reach the standard of MahApps. If there is a way for me to help,  please let me know. 
At the moment I am trying to improve the toggle switch button, especially the intermediate state.  I will place a pull request and see if it is good or not 🙃

----- Nachricht beantworten -----
Von: "Gary Ewan Park" <notifications@github.com>
An: "MahApps/MahApps.Metro" <MahApps.Metro@noreply.github.com>
Cc: "timunie" <tim.uniewski@gmail.com>, "Comment" <comment@noreply.github.com>
Betreff: [MahApps/MahApps.Metro] Proper Windows 10 style (#3508)
Datum: Di., Mai 28, 2019 19:04

@Symbai any negative feedback you received is likely due to the way in which you phrased the problem that you are seeing.  I know you say that you were trying to ask it nicely, but I, and obviously others didn’t think it came across that way.
A far better way to approach this would have been to ask “how can I help”, or “where would be a good place to start looking at testing/fixing this”?
Unless there is another issue in this repo specifically requesting this addition, I personally would suggest that it should be re-opened so that it can be tracked.

&mdash;You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gep13** [comment]
>@timunie said...
So code produced by me might not reach the standard of MahApps. If there is a way for me to help,  please let me know.

I can't speak for @punker76 but I would say, based on my experience with working with him in Open Source, that he would be more than willing to provide guidance on any PR that is raised in this repository.  If you are not sure about something, perhaps start the PR, and then ask questions on the lines that you are not sure on.  Then @punker76 and other contributors to the project will be able to advice.

While I am not able to contribute to this project, I am a consumer of it, and I choose to support the project through [Open Collective](https://opencollective.com/mahappsmetro) which is another way to support the project.

**Comment by Symbai** [comment]
The owner is welcome to reopen the issue if he like but I don't since I don't like to open a ticket requesting on something that isn't really accepted by the majority. I've taken the feedback as an answer on my question and therefore closed the request as I believe there is no value in it. Thanks for considering it though.

**Comment by batzen** [comment]
My feedback wasn't meant negative. But as you noticed yourself work on this hasn't started for a long time and there are already open issues for this. So if you want work to start on this you can just go ahead and start the work.
So my feedback was meant to point out "if you want something to be done, do it yourself", but not in a negative way.
If you need help, guidance, advice or something like that feel free to mention me and I'll try to help as much as I can.
