### ISSUE TITLE
Button with a click event in the flyout does not work well on a touchpad. PC(mouse click) works well.

### ISSUE THREAD

**Issue by Weijee** [MahApps/MahApps.Metro#3545]

**Comment by punker76** [comment]
@Weijee 

>Button with a click event in the flyout does not work well on a touchpad.

What exactly did you mean? It doesn't work? Or is there a bug? Or something else?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
