### ISSUE TITLE
Multiple ListViews with multiple items slows down switching views

### ISSUE THREAD

**Issue by Hanebu** [MahApps/MahApps.Metro#3554]
# Multiple ListViews with multiple items slows down switching views #

I am using the HamburgerMenu as navigation and Caliburn.Micro as MVVM Framework.
I got 3 Views besides the Shellview, ViewA and ViewB are only containing a few items like TextBlocks, TextBoxes and ComboBoxes. Switching between those is really smooth and very well animated (using Transition="RightReplace"). ViewC is containing 8 ListViews with custom ListViewItemStyle, as long as they are empty everything is smooth here aswell. As soon as I add items to those ListViews the navigation **from** and **towards** ViewC is pretty slow. The interaction with each ListView itself is fine. The navigation even slows down if I only add 2 items to each ListView. No animation is showing at all, the whole UI freezes for some time (depending on the amount if items in the ListViews)

**I tested so far:**
- "VirtualisedMetroListView", no change in the behaviour.
- "WrapPanel", "VirtualizingStackPanel", "StackPanel" and setting the Virtualizing options manually in each Listview, no change in the behaviour.
- Removing MahApps.Metro completly, solves the to 95%. It speeds up alot, but still missing some milliseconds compared to empty ListViews (and the App looks ugly now...)
- Removing custom ListViewItemStyle, removes the slowdown when **loading** ViewC, but **leaving** from ViewC is still slowed down.

**Environment:**
 - MahApps.Metro v2.0.0-alpha0391
 - OS: Win10 v1809
 - Visual Studio 2019 v16.1.6
 - .NET Framework v4.5.2

I have no Idea what else I can try or do to prevent the App from slowing down that much.

**Comment by punker76** [comment]
@Hanebu Can you create an app with this behavior? Thx.

**Comment by Hanebu** [comment]
Of course! [Here you go...](https://github.com/Hanebu/MahAppsListViewDemo)

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
