### ISSUE TITLE
Themes.xaml --> Sould it be Gray or Grey?

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro#3575]
**Describe the bug**
I really like the way the theme resources are called now, because it is more intuitive. But what i don't understand is, the Name of the Gray Brushes. 

Have a look in the file Theme.xaml: 

```
    <SolidColorBrush x:Key="MahApps.Brushes.SemiTransparentGrey" Color="#40808080" options:Freeze="True" />

[....]

    <SolidColorBrush x:Key="MahApps.Brushes.Gray1" Color="{StaticResource MahApps.Colors.Gray1}" options:Freeze="True" />
```

**To Reproduce**
Just have a look here: 
[https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Themes/Theme.Template.xaml](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Themes/Theme.Template.xaml)

**Expected behavior**
I am not a native english speaker, so I cannot tell you which spelling for gray or grey is the correct version. But we should use only one version imo. 

**Screenshots**

**Environment(please complete the following information):**
 - MahApps.Metro version 2.0.0 latest alpha

Happy coding 
Tim

**Comment by makingbloke** [comment]
I vote for grey being a British English speaker :) too much Americanisation
of our language going on lol ;)

**Comment by amkuchta** [comment]
@makingbloke the fact that you have "bloke" in your username confirms that you are, in fact, British.

As an American, I actually side with @makingbloke - I personally prefer the British spelling of the word.

**Comment by punker76** [comment]
@timunie The `Grey` was introduced by this [PR](https://github.com/MahApps/MahApps.Metro/pull/2152).

I would prefer changing this to `Gray` because it's just these 2 places.

**Comment by timunie** [comment]
@punker76 I think you are right. Then it would be easier for other people, too. 

Happy coding
Tim

**Comment by Evangelink** [comment]
Usually in IT american english wins over british ;)

**Comment by makingbloke** [comment]
Hey we’ve got to give them some concession :) Us Brits invented the
language - the Americans bastardised a dialect lol :)

**Comment by Jehoel** [comment]
(I'll preface my answer by saying I'm British myself, albeit living in Microsoft's back-yard in Redmond)

Putting national-pride aside - the official .NET Framework Style Guidelines do make it clear that `en-US` spelling should always be preferred, and because it's consistent with the main .NET class libraries which use `en-US` spelling, especially in `System.Drawing.Colors` where it's `Gray`, not `Grey`, sorry: https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color.gray?view=netcore-3.1

I feel a small insignificant cringe whenever I review Unity (game-engine) code because they named one their main interfaces `Behaviour` rather than `Behavior` - I stress it's not the fact it's not en-US, but the fact it's inconsistent.

I can imagine a non-native English speaker who might be completely oblivious to the differences between `Grey` and `Gray` who is converting WinForms+GDI code to WPF+`MahApps.Metro` at 3am and just pounding their head on the keyboard because their code won't compile because they didn't expect something as simple as colour names to be arbitrarily different compared to the rest of the .NET library ecosystem.

If we want MahApps.Metro to counter Americanism (I won't go as far as saying "cultural imperialism"[1]) in the software industry it should be by embodying the best parts of British values, not something as patently silly as spelling. Pink Floyd said it best in 1973:

> Hanging on in quiet desperation is the English way

...but I'll also settle for the `MahApps.Metro` library including a GIF of Queen Liz and her corgies as an easter-egg hidden inside the main assembly.

[1] And that would be inexcusable coming from someone who indirectly benefited from the spoils of the days of Empire...
