### ISSUE TITLE
Visual Studio Extension (VSIX) support

### ISSUE THREAD

**Issue by Enache-Ionut** [MahApps/MahApps.Metro#3670]
Hi, 

I'm trying to include Mahapp.Metro NuGet package in my Visual Studio extension project. I'm using VS 2019 and .Net Framework 4.6. In designer mode, the controls look good. I'm trying to replace my check-boxes with toggle-switches. This is a print from the designer mode.

![image](https://user-images.githubusercontent.com/10616921/68009643-2e5cd400-fc8b-11e9-8528-22069aa38d17.png)

When I run my project and my windows should pop-up, I get this error every time:

System.Windows.Markup.XamlParseException: 'Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.'

FileNotFoundException: Could not load file or assembly 'MahApps.Metro, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Do you know how I can solve this? 

Mahapps.Metro is compatible with Visual Studio Extension (VSIX) apps?

**Comment by timunie** [comment]
Hi @Enache-Ionut 
do you have [this](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start) in your `App.xaml` ?

Happy coding
Tim

**Comment by Enache-Ionut** [comment]
No, working with Visual Studio extensions is a little bit different. I don't have an `App.xml` file. To use my custom wpf windows I simply instantiate a window and then show it like this:

`
MyWindow myWindow = new MyWindow(); 
myWindow.ShowDialog();
`

Do you have a solution for VSIX projects?

**Comment by timunie** [comment]
Hi @Enache-Ionut 

sorry I didn't get this. Are you able to add the resources in your `Window` ? I am not fimilar with VSIX projects 😞 

Happy coding
Tim

**Comment by Enache-Ionut** [comment]
In the meanwhile, I implemented a toggle-switch by hand. Yes, my app can include resources but I'm not sure if it will work like in your example. Maybe it is enough to add the resources in my main `ResourceDictionary` file. I will update this thread after I will try this.

Regards,
~Ionut

**Comment by punker76** [comment]
@Enache-Ionut Can you publish your extension here on GitHub? Which version of MahApps do you use?

**Comment by AKruimink** [comment]
@Enache-Ionut  Any news on this? 
Most extentions i have seen (including the github for visual studio extension) load resources in  their respective `Window` like @timunie suggested, which can be set by using `Window.Resources`

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
