### ISSUE TITLE
Use with ControlzEx 4.2.1

### ISSUE THREAD

**Issue by jogibear9988** [MahApps/MahApps.Metro#3733]
How can I use the Nugeht while also using ControlzEx 4.2.1? Cause it requires a lower Version

**Comment by timunie** [comment]
Hi @jogibear9988 ,
which verison of MahApps do you use?

Happy coding, 
Tim

**Comment by jogibear9988** [comment]
1.6.5,

**Comment by jogibear9988** [comment]
And some lib I use Reference 4.xx

**Comment by timunie** [comment]
then you will need v2.0.0 alpha

**Comment by jogibear9988** [comment]
when will it be production ready?

**Comment by timunie** [comment]
Hi @jogibear9988 ,

it is a free time project maintained by almost only @punker76 . So I think there is no fixed release date, but we are close to release v2.0 as far as I know. I updated all my projects already, because the prerelease is more stable and less buggy than the current v1.6.5 (from my point of view).

Happy coding,
Tim

**Comment by punker76** [comment]
@jogibear9988 I'm working on it, sorry for the delay...

**Comment by marcosgerene** [comment]
@punker76

First, congratulations by the project, it is amazing!

What's missing for realease the v2.0.0?

**Comment by batzen** [comment]
One large missing part is my work on the generic ThemeManger and RuntimeThemeGenerator in ControlzEx. Can't say much about other missing parts.

**Comment by marcosgerene** [comment]
@batzen 

Thanks for the informations
