### ISSUE TITLE
Right-/LeftWindowCommandsOverlayBehavior option Always missing

### ISSUE THREAD

**Issue by KrabatTilt** [MahApps/MahApps.Metro#3754]
I updated to latest alpha and Flyouts now overlay(hide) the Left- and RightWindowCommads content. I get an xaml error telling me that the option RightWindowCommandsOverlayBehavior="Always" is not available any more. 
Is it intended that the ability of Left- and RightWindowCommads to overlay flyouts is now missing. Or is there a new way to achieve the previous behavior?

**Environment**
 - MahApps.Metro version [2.0.0-alpha0660]
 - OS: [Win10 1909]
 - Visual Studio [16.4.5]
 - .NET Framework [netcoreapp3.1]

**Comment by punker76** [comment]
@KrabatTilt Yes, this was changed in this PR #3511 , because of this change #3503 to the WindowCommands. (take also a look to [this](https://github.com/MahApps/MahApps.Metro/issues/3604#issuecomment-531670658) )

The default for the left and right window commands behavior is set to `WindowCommandsOverlayBehavior.Never`. So if you set `ShowTitleBar` to false they will not shown and will now also not shown over flyouts. They only visible if you set this to `WindowCommandsOverlayBehavior.HiddenTitleBar`.
