### ISSUE TITLE
DataGrid Cell edit Theme issue

### ISSUE THREAD

**Issue by thedimm** [MahApps/MahApps.Metro#3766]
It seems DataGrid cell edit context menu ignores the theme 

![NOK](https://user-images.githubusercontent.com/7725107/77356025-ea429c80-6d1b-11ea-859a-f5dd7f564f7d.jpg)

![OK](https://user-images.githubusercontent.com/7725107/77356033-ee6eba00-6d1b-11ea-9ffe-582ec2f8f452.jpg)

**Comment by punker76** [comment]
@thedimm This is fixed in latest source (also available at NuGet as pre-release). Keep in mind that there are many breaking changes in there.

https://github.com/MahApps/MahApps.Metro/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Breaking+Change%22+milestone%3A2.0.0

https://github.com/MahApps/MahApps.Metro/issues?q=is%3Aissue+is%3Aclosed+milestone%3A2.0.0+label%3A%22Breaking+Change%22

![image](https://user-images.githubusercontent.com/658431/77361190-293e1580-6d4f-11ea-83fd-c5760af4617a.png)

**Comment by thedimm** [comment]
Hello plunker76 . Any plans to fix in 1.6 ? 
IF not when will 2.0.0 be released?

**Comment by punker76** [comment]
@thedimm Due date is May 01, 2020 (that's the plan, if there is no other catastrophe)
