### ISSUE TITLE
Toggling visibility on hamburger menu

### ISSUE THREAD

**Issue by WPFAdvocate** [MahApps/MahApps.Metro#3768]
It would be nice to have a visibility open on hamburger menu items to hide from people that are not suppose to see instead of just it being disabled for certain users.

**Comment by bNobo** [comment]
I've started working on it and have a question: should `Visibility` property be added on `HamburgerMenuItem` or `HamburgerMenuItemBase` class? In the first case it won't be possible to hide or collapse a menu separator because `HamburgerMenuSeparatorItem` inherits from `HamburgerMenuItemBase`. Should the menu separator also be able to be hidden?

**Comment by timunie** [comment]
Hi @bNobo 
Consider this:
```
Item1
-----------
Item2
-----------
Item3
```
If you hide Item2 you would have two seperators. So in that case you must be able to hide the seperator as well. 

That said please keep in mind that the primary goal is to get v2.0.0 released. this feature might get implemented later. 

Happy coding
Tim
