### ISSUE TITLE
DateTimePicker size to wide and always close when select time (hour, min)

### ISSUE THREAD

**Issue by hunggiangg** [MahApps/MahApps.Metro#3776]
**Describe the bug**
DateTimePicker size to wide and always close when select time (hour, min)
Hello, I have an issue with datetimepicker of Mahapp, it seems to be too wide and when I click to hour or minute, this action closes the datetimepicker. Pls help me to solve this issue.

My XAML  code:
`<Controls:DateTimePicker x:Name="DateTimePicker"
                                                             Culture="vi-VN"
                                                             HandVisibility="HourMinute"
                                                             IsClockVisible="True"
                                                             PickerVisibility="HourMinute"
                                                             SelectedDateFormat="Short"
                                                             SelectedTimeFormat="Short"
                                                             Margin="5,0,0,0"
                                                             Width="200">
                                    </Controls:DateTimePicker>`

**Screenshots**
![image](https://user-images.githubusercontent.com/63958381/79687731-8c01ce80-8273-11ea-96a8-21379a9ea10b.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1909
 - Visual Studio 2019 community 16.5.2
 - .NET Framework 4.6.1

**Comment by timunie** [comment]
Hi @hunggiangg ,

there seems to be something wrong with your App. It would be helpful if you can give us access to your App or provide a sample project. I think there is an issue in your `App.xaml`

Happy coding
Tim

**Comment by hunggiangg** [comment]
Hi @timunie ,

Thank for your quick response, here is my sample project, pls take a look and help me to find a solution.

Happy coding
Hung


[HoangPhatManagement - Copy.zip](https://github.com/MahApps/MahApps.Metro/files/4501019/HoangPhatManagement.-.Copy.zip)

**Comment by timunie** [comment]
Good news, I have a solution for you

here is my result: 
![image](https://user-images.githubusercontent.com/47110241/79717069-df5a3800-82d8-11ea-889a-2eadafdc4fcf.png)

The problem is that you override the `Styles` in your XAML

1) use a base style: 
```xaml
<Style TargetType="ComboBox" BasedOn="{StaticResource {x:Type ComboBox}}">
```

2) don't set the `Width`-Property in the `Style` because it applies to all `Label` and `ComboBox`. Just remove this:
```xaml
<Setter Property="Width" Value="200" />
```

3) you set `Focuable=false` on the `ComboBox`. This removes the `Focus` from the `DateTimePicker` and tells the `Popup` to close. So please remove this: 
```xaml
<Setter Property="Focusable" Value="False" />
```

4) You can also define your custom `Styles` in `App.xaml` so you have it globally applied. You may also use different `Styles` by giving them a `Key` `x:Key="YourKeyGoesHere"` and use it in your control via:
```xaml
<ComboBox Style="{StaticResource YourKeyGoesHere}" />
```

Hope it helps & Happy coding again
Tim

**Comment by hunggiangg** [comment]
Thank you so much, your solution is totally working.
I will change all `style` to `App.xaml` to make reuse code.

Have a good day.
Hung.
