### ISSUE TITLE
Dialog isn't visible to close

### ISSUE THREAD

**Issue by TripleNico** [MahApps/MahApps.Metro#3832]
Let me first start with my compliments of the release of 2.0 and also with the new website, very nice! A lot of work has been done and i really appreciatie the effort!

From different places i call sub routine to open and display a Indeterminate dialog. However when i try to close it (also called from different threads) then i get a exception "Dialog isn't visible to close"

I noticed that the behaviour is the same from 1.6.4 or 2.0

Opening code:
```vb
Private Async Sub Sync_Manager_SyncRunning(Sync As String, State As SyncManager.SyncState) Handles Sync_Manager.SyncRunning
    Try
        Select Case State
            Case SyncManager.SyncState.Running
                If DialogController Is Nothing OrElse Not DialogController.IsOpen Then

                    Await Dispatcher.Invoke(Async Function()
                                                DialogController = Await Me.ShowProgressAsync("Taak", $"{Sync.Replace("Sync", "")} wordt uitgevoerd...", True)
                                                Return True
                                            End Function)

                    DialogController.SetIndeterminate()
                Else
                    DialogController.SetMessage($"{Sync} wordt uitgevoerd...")
                End If

            Case SyncManager.SyncState.Stopped

                If Not Sync_Manager.blnSyncRunning Then Await CloseVisibleDialogs()
        End Select
    Catch ex As Exception
        log.Exception(ex)
        ShowError(ex.Message)
    End Try
End Sub
```

Closing code:
```vb
Public Async Function CloseVisibleDialogs() As Task
    Try
        Await Me.Dispatcher.Invoke(Async Function()
                                       If DialogController IsNot Nothing AndAlso DialogController.IsOpen Then Await DialogController.CloseAsync()
                                       Return True
                                   End Function)
    Catch ex As Exception
        log.Exception(ex)
        ShowError(ex.Message)
    End Try
End Function
```

The exception that i get is on `DialogController.CloseAsync()` but if i check if `DialogController.IsOpen` then this is still True. The `DialogController` is declared global

So what am i doing wrong?

**Comment by punker76** [comment]
@TripleNico Thanks for the flowers 👍  Sorry that you get this issue, but I am a bit rusty with Visual Basic. Hopefully one of the community members can help!

**Comment by timunie** [comment]
@TripleNico any chance you can post a demo App for your issue? I am not able to get this to run, because of some missing references.

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
