### ISSUE TITLE
Visual error on some computers

### ISSUE THREAD

**Issue by dnobrerochapt** [MahApps/MahApps.Metro#3886]
Hello,

I have an application developed with the Mahapps template. The problem is that on some computers, the application behaves strangely visually.

When I click on a combobox, the list appears in the upper right corner of the screen. The flyout also appears misshapen.

This happens on some computers with Windows 10 and also with Windows 8. The computers has only one screen

I'm using the Mahapps 1.6.5 release.

Strangest of all, this error does not always happen! On the same computer when I open the application it sometimes happens and sometimes it doesn't.

![image1error](https://user-images.githubusercontent.com/68443882/87824513-cb789080-c84b-11ea-80d6-59555a229acd.jpg)

![image2error](https://user-images.githubusercontent.com/68443882/87824603-f367f400-c84b-11ea-86e7-454a621317a8.jpg)

**Comment by timunie** [comment]
Hi @dnobrerochapt 

Can you make a small sample App on github and test this with 1.6.5 and 2.1.1?  You may also test it with the demo App. 

please note that v1.6.5 will not be maintained any further. If the issue still exists in 2.x it should be investigated further. 

Happy coding
Tim

**Comment by dnobrerochapt** [comment]
Ok, i will upgrade to version 2.1.1.

But this error is very strange. It only happens on some computers and not others.

I already thought that it may be some Windows update that causes some incompatibility.

**Comment by timunie** [comment]
@punker76 this is also what I sometimes see on Win7 with PopupEx. May be it is related to my positioning issue we talked in gitter some days ago?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
