### ISSUE TITLE
Menu style on the right side

### ISSUE THREAD

**Issue by Suplanus** [MahApps/MahApps.Metro#3891]
## Describe the bug

If a menu is on the right side of the display, the menu expands to the left.  
There is a space between the submenus. 

## Expected behavior
Example from Visual Studio:
![image](https://user-images.githubusercontent.com/2002916/88283026-f26f1080-ccea-11ea-8760-0f64f9cadd16.png)

## Actual behavior
MahApps:
![image](https://user-images.githubusercontent.com/2002916/88283017-eedb8980-ccea-11ea-833c-e82a42efe498.png)

## Environment

```
MahApps.Metro version: v2.1
```

**Comment by Gimly** [comment]
It looks to be trickier to fix that it should. The spacing between the menu seems to be defined by the `HorizontalOffset` of the `Popup` in this part of the `MenuItem` template:
https://github.com/MahApps/MahApps.Metro/blob/a65d52e08c574321fbb63a2b09fbe301c83238f3/src/MahApps.Metro/Styles/Controls.MenuItem.xaml#L391-399

Setting it to `6` instead of the `-2` makes it work nicely as in the top screenshot when the menu opens to the left. Unfortunately, it adds the gaps when it opens to the right 😄.

I can't find any way to set a different horizontal alignment depending on whether it's opened on the right or on the left. There's a popup placement callback, but we can't use it there since we're in a template.
