### ISSUE TITLE
Add .NET 5 support

### ISSUE THREAD

**Issue by AzureZeng** [MahApps/MahApps.Metro#3971]
## Describe the feature

Now .NET 5 is released and I want to migrate the target framework of my WPF project(used MahApps.Metro) to .NET 5. So I need this library to support .NET 5.

**Comment by punker76** [comment]
This will be done after doing this with ControlzEx.

**Comment by ourplan9000** [comment]
DateTimePicker no 24-hour system

**Comment by punker76** [comment]
> DateTimePicker no 24-hour system

@ourplan9000 ?

**Comment by auxua** [comment]
Can someone give an update on the .Net 5 compatibility/state at the moment? As I see, ControlzEx should be compatible - Is there an .Net 5 preview of MahApps?

**Comment by timunie** [comment]
Hi @auxua 

as you cleary can see it is marked with the `3.0.0`-Milestone. So there is a plan, but as this is a **free-time** project it will be done when there was enough free time. 

Asking frequently will not make the release happen earlier. 

Thank you for your understanding & happy coding
Tim

**Comment by punker76** [comment]
@auxua It's coming... ControlzEx will be available in next weeks, after that the 3.0 of MahApps will start, after the fixes for 2.4.4

**Comment by crippledfaith** [comment]
Will compatibility come for .net 5?

**Comment by timunie** [comment]
@crippledfaith it is in work. 🚧 Please be a bit patient because it is a fee time project and it's done when it's done. Give it a bit more time.

Happy coding
Tim

**Comment by grschtroumpf** [comment]
Hello, just to give a small feedback on that topic...
First of all, I love this project, I use it for years and it's beautiful!
Congrats to the dev team, you're doing an amazing job!

About .Net 5, I did the migration (.Net Framework to .Net 5) of one of my personal projects and everything seem to work fine with MahApps, so that's really great news!  🥇 

During the build I just have a few warning:

warning CA1416: This call site is reachable on all platforms. 'ThemeManager.Current.get' is only supported on: 'Windows' 7.0 and later.
warning CA1416: This call site is reachable on all platforms. 'ThemeManager.SyncTheme()' is only supported on: 'Windows' 7.0 and later.
warning CA1416: This call site is reachable on all platforms. 'ThemeSyncMode.SyncAll' is only supported on: 'Windows' 7.0 and later.

According to Microsoft (about CA1416):

_Cause_
_Violations are reported if a platform-specific API is used in the context of a different platform or if the platform isn't verified (platform-neutral). Violations are also reported if an API that's not supported for the target platform of the project is used._

_This rule is enabled by default only for projects targeting .NET 5.0 or later. However, you can enable it for projects that target other frameworks._

**Comment by GWawrzeniecki** [comment]
We are waiting patiently
