### ISSUE TITLE
Enhancing DataGrid.RowStyle

### ISSUE THREAD

**Issue by JLTook11** [MahApps/MahApps.Metro#4158]
Similar to https://github.com/MahApps/MahApps.Metro/issues/1492 ?

The following works fine to change the Background when IsPlayer is True -- however, the other MahApps DataRow DataTriggers will no longer fire (e.g. row is selected or highlighted / mouse over).  Not sure how to simply add this behavior without affecting any of the existing triggers -- and may or may not be specific to MahApps.

	<DataGrid.RowStyle>
		<Style TargetType="DataGridRow"  BasedOn="{StaticResource MahApps.Styles.DataGridRow}">
			<Style.Triggers>
				<DataTrigger Binding="{Binding IsPlayer}" Value="true">
					<Setter Property="Background" Value="{StaticResource MahApps.Brushes.Accent4 }"></Setter>
				</DataTrigger>
			</Style.Triggers>
		</Style>
	</DataGrid.RowStyle>

Thanks!

**Comment by timunie** [comment]
Hi @JLTook11 

I think the issue here is, that the original `Triggers` are overridden by your owns. You can try to copy&paste the original ones to your `Style` and see if it works for you: 
https://github.com/MahApps/MahApps.Metro/blob/91002e95f1acc6b69c7f3a290a46afffb82e44ba/src/MahApps.Metro/Styles/Controls.DataGrid.xaml#L596-L656

Happy coding 
Tim

**Comment by timunie** [comment]
I am not sure, at least I didn't find something. Moreover when there is such a concept it's not MahApps related. So please close this issue if it's solved for you 🙏

Thx
Tim

**Comment by JLTook11** [comment]
Yes, mostly a WPF concept / issue (unless there was something the MahApps styles could change to make this possible).

Closing... thanks again!
