### ISSUE TITLE
ShowMessageAsync appears under WebBrowser

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [MahApps/MahApps.Metro#4164]
ShowMessageAsync appears under WebBrowser, on no other control I have such a problem, only with WebBrowser, which is always higher than ShowMessageAsync

XAML
`<WebBrowser x:Name="webBrowserOutputData" Margin="10,130,10,10" />`

C#
`this.ShowMessageAsync("Error!", "Select", MessageDialogStyle.Affirmative);`

## Environment

```
MahApps.Metro version: v2.4.7
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework:  v4.7.2
```

## Screenshots
![obraz](https://user-images.githubusercontent.com/71566296/130051600-fcad0469-39dc-496f-8120-c37faef52af9.png)

**Comment by punker76** [comment]
@cosmicDustOfLightLength This issue is known for WPF. You can try using an `AirspaceDecorator` like

```xaml
<interop:AirspaceDecorator x:Name="PreviewAirspaceDecorator"
                           Grid.Row="1"
                           AirspaceMode="Redirect"
                           Background="Transparent"
                           IsInputRedirectionEnabled="True"
                           IsOutputRedirectionEnabled="True">
    <WebBrowser x:Name="WebBrowser" Source="https://mahapps.com" />
</interop:AirspaceDecorator>
```

with the namespace `xmlns:interop="clr-namespace:Microsoft.DwayneNeed.Interop;assembly=Microsoft.DwayneNeed"`

and the compiled assembly `Microsoft.DwayneNeed` from https://github.com/MahApps/Microsoft.DwayneNeed

![image](https://user-images.githubusercontent.com/658431/130057140-2a48bcb2-71e5-46ca-a55a-e9ceb1c0de30.png)
